elan-ev/studip-opencast-plugin

plugin.manifest
Dieser Patch behebt eine Reihe von Kodierungs- und Textfehler in der
Beschreibung des Plugins.
This fixes #75
=> Fehlerbehebung der Beschreibung

views/course/_upload.php
=> Anpassung des Upload-Hinweistextes auf §60.

models/OCCourseModel.class.php, views/course/index.php
=> refined some code and enabled presentation preview.

classes/OCRestClient/OCRestClient.php, controllers/course.php, views/course/index.php
=> fixes #123

INSTALL.md
=> INSTALL notes: document republish metadata workflow name required

views/course/upload.php
=> Allow only video files to be uploaded

views/course/upload.php
=> Upload: Force file selection

stylesheets/oc.less, views/course/upload.php
=> increase max-width of date/time input fields on media upload page

classes/OCRestClient/SeriesClient.php
=> `urlencode` the POST parameters while creating a series

classes/OCRestClient/ApiEventsClient.php, classes/OCRestClient/ApiWorkflowsClient.php, controllers/course.php, migrations/030_add_is_retracting_flag_to_episodes.php, models/OCCourseModel.class.php, models/OCModel.php, views/course/_episode.php
Dieser PR fügt einen weiteren Button hinzu, der es einem Dozierenden ermöglicht, Aufnahmen zu löschen.
Refs #48
=> Episoden löschen 

classes/OCRestClient/ApiEventsClient.php, controllers/course.php, views/course/_episode.php
Ich hab wie in #143 empfohlen einen Link zum Schnitteditor hinzugefügt. @CGreweling schaut noch noch, wie man herausfindet, ob man schon schneiden darf.
=> add link to video editor, refs #143

controllers/course.php, controllers/upload.php, javascripts/application.js, views/course/index.php, views/course/upload.php
Das ist mein gegenwärtiger und unvollständiger Stand. Der Upload scheint zunächst einmal zu funktionieren. Im Moment werden noch keine Rückmeldungen an die UI bzgl. Erfolg, Fehler oder Progress gegeben. Das sieht man gerade nur in der Konsole.
=> Upload media via LTI instead of the chunked uploader

OpenCast.class.php
=> overwrite getPluginName to spell Opencast correctly

stylesheets/oc.less
https://github.com/elan-ev/studip-opencast-plugin/issues/225
=> fixed preview image distortion

controllers/course.php, views/course/_episode.php
=> preclude users with perm level `user` from watching episodes

classes/OCRestClient/ACLManagerClient.php, classes/lti/OpencastLTI.php
=> prevent error after re-creating an already existing ACL

views/course/index.php
- Tutoren und alle Lehrende sehen "unsichtbare" Videos (nicht nur "Sie")
- Requires translation
=> Episode visibility dialog texts

INSTALL.md
=> Installation notes: Provide nginx config for CORS

INSTALL.md
Added confoguration options for the new LTI-Upload and OC-Studio
maybe fixes #274
=> Add configuration for oc-Studio and LTI-Upload

INSTALL.md
cf. https://github.com/elan-ev/studip-opencast-plugin/blob/81007bcc5d8d3ea4db6c7113a676bc0c72f8a08b/classes/OCRestClient/ApiWorkflowsClient.php#L24
=> INSTALL.md: retract WF ID needs to be retract

.babelrc, .gitignore, OpenCast.class.php, javascripts/application.js, package-lock.json, package.json, webpack.config.js
In #229 wünscht sich @Rillke , dass das Plugin dieselbe Browserkompatibiliät wie Stud.IP bietet. Mit webpack und babel geht das leicht.
Fixes #229
=> Webpack und Babel integrieren

javascripts/application.js, stylesheets/oc.less, views/course/upload.php
Mit diesem PR können Lehrende nun zwei Videos hochladen.
Fixes #277
=> Dual-Upload

classes/OCRestClient/ApiEventsClient.php, classes/OCRestClient/WorkflowClient.php, controllers/course.php, plugin.manifest, views/course/_episode.php, views/course/_wip_episode.php, views/course/index.php
=> List running events

controllers/admin.php, controllers/course.php, plugin.manifest, views/admin/config.php, views/course/index.php
=> remove unnecessary actions

stylesheets/oc.less, views/course/_episode.php
=> add icons to video actions, improved mobile display (#226)

javascripts/application.js, views/course/upload.php
=> Attach ACL to Upload

views/course/upload.php
If there is no ROLE_ADMIN in the episode ACL search does not find the episode with the plugin opencast user
=> add ROLE_ADMIN R/W to acl

images/opencast-black.svg, images/opencast-grey.svg, images/opencast-red.svg, images/opencast-white.svg, images/opencast.svg
little fix of icon size in consistency to the other stud.ip icons.
=> icon size 16x16

controllers/course.php
=> Check for a series connection before creating one more

views/course/upload.php
Don't include user_read_Permit in Upload-ACL if HIDE_EPISODES is set.
=> HIDE_EPISODES in ACL beachten

OpenCast.class.php, controllers/course.php, views/course/index.php
=> OC Plugin in Studiengruppen

cronjobs/refresh_scheduled_events.php, javascripts/application.js, models/OCSeriesModel.php, views/course/upload.php
Kann mit #368 kombiniert werden
=> Dateien mit langen Dateinamen -- fix372

classes/OCRestClient/SchedulerClient.php, models/OCModel.php
Fixx Fehlermeldung beim Aufruf des Schedulers in Version > 4.4
=> Abrufen der Datenbanktabellen nun versionsabhängig

models/OCCourseModel.class.php
=> Parenthesize media download condition correctly

controllers/course.php, models/OCCourseModel.class.php, views/course/_episode.php
Bin mir noch unsicher, ob die gewählten Offsets die richtigen Sortierungen auslösen
title -> TITLE
start -> DATE_PUBLISHED
mkdata -> DATA_CREATED
=> fix 227 - Sortierung der Episoden

classes/OCRestClient/AdminNgClient.php, classes/OCRestClient/AdminNgEventClient.php, constants.php, controllers/course.php
Endpoint wird nicht Eingebunden (wird nicht in DB oc_endpoints angezeigt).
=> "Entfernen" führt nur retract aus, sollte aber komplett löschen -- Fix 362

OpenCast.class.php, constants.php, controllers/course.php, javascripts/application.js, locale/en/LC_MESSAGES/opencast.po, migrations/013_add_precise_config.php, views/admin/resources.php, views/course/index.php, views/course/upload.php, views/course/workflow.php
Upload in Hochladen geändert.
Die opencast.po hab ich auch entsprechend angepasst, aber kein translation command laufen lassen
=> Upload oder Hochladen? #384

views/course/upload.php
=> Remove typo in source code

OpenCast.class.php, views/course/index.php
=> E-Mail Adresse für LTI Nutzer mit an Opencast übertragen #407

classes/OCRestClient/OCRestClient.php, constants.php
=> Überflüssige Konfigurationsoptionen entfernen #409

migrations/033_improve_config.php
- 035: ✅
- 034: In TOS wird null geschrieben, ist das ok?
- 033: ✅ Voreinstellungen von oc_config_precise werden wiederhergestellt
settings von oc_config werden übernommen (es gibt aber keine description)
#417
=> Downgrades durchtesten

OpenCast.class.php
=> Unsichtbarkeitshinweis in den Titel des Opencast-Tabs #402

javascripts/application.js, views/admin/_initial_config.php
Bei LTI Anmeldung wird bei einem Error eine Fehlermeldung ausgegeben.
Das sollte in VA schon funktionieren. (Nicht getestet)
Wurde im Adminbereich noch nicht getesetet!
Besser wäre auch noch eine andere Fehlermeldung im Adminbereich
=> LTI-Anmeldung prüfen #404 

OpenCast.class.php, controllers/course.php, models/OCCourseModel.class.php, models/OCModel.php, package-lock.json, views/course/_episode.php, views/course/index.php
=> Studygroup fix

classes/OCRestClient/ApiEventsClient.php, classes/OCRestClient/SeriesClient.php, classes/lti/OpencastLTI.php, models/OCCourseModel.class.php, views/course/index.php, views/course/upload.php
=> upload visibility for course

javascripts/application.js, views/admin/_initial_config.php
=> LTI url fix

classes/OCRestClient/ApiEventsClient.php, controllers/course.php, views/course/_episode.php
#328
Habs mit dem Link des Schnitteditors getestet, sollte mit dem channel 'annotation-tool' also auch funktionieren.
Die class des Buttons muss angepasst werden, der sieht momentan so aus wie der vom Schnitteditor
=> Annotation-Tool Link hinzugefügt

controllers/course.php
=> Tutoren können die Sichtbarkeit des Reiters nun ändern

javascripts/application.js, views/admin/_initial_config.php
=> Größe des Fensters der LTI Fehlermeldung angepasst

OpenCast.class.php
=> Icon für Studierende in Veranstaltungsübersicht ausblenden, wenn Reiter unsichtbar

views/course/upload.php
Sometimes login times out or, since LTI login is automatic,
you log in as another user in a different tab, or you just
have bookmarked the upload form.
Resolves #449
=> LTI login from upload form

controllers/course.php, views/course/index.php
Currently admins can upload and schedule but do not have to agree to
ToS.
Closes #448
=> Force ToS for Stud.IP Admins

cronjobs/refresh_scheduled_events.php
which are not associated with any Stud.IP event
=> Log events being deleted in Opencast by Cronjob

README.md
=> Abschnitt Fallstricke, ergänzt mit Lösch-Cronjob

README.md
Das sind so die Support-Anfragen und die Überraschungen, die unser Kunde gemeldet hat.
=> README: Weitere Fallstricke und Einschränkungen

classes/OCRestClient/SearchClient.php
=>  "Only" first 2000 series available when connecting series to Stud.IP course

controllers/course.php, migrations/038_add_log_tos.php
=> Log Eintrag für TOS

views/course/_episode.php
=> Zeige bei Sortierung gerade ausgewählte Sortierung an

OpenCast.class.php, classes/OCPerm.php, controllers/course.php, migrations/041_add_upload_studygroup.php, models/OCModel.php, models/OCUploadStudygroup.php, views/course/index.php
=> Studiengruppenverknüpfung: Migration für Konfigurationseinstellungen fehlt

controllers/admin.php, controllers/course.php, views/admin/_initial_config.php, views/course/index.php
=> Meldung über nicht aktiviertes OC Plugin in Studiengruppen in den Admin-Bereich #482

javascripts/application.js
Resolves #489
by creating a new file object from the old one. [Users report](https://stackoverflow.com/a/50011806/2683737) that a reference to the old File is used and memory consumption is not increased.
=> Fix JS error if upload len(upload file name)>128

models/OCCourseModel.class.php
=> is_part_of:Array #487

OpenCast.class.php, bootstrap.php, controllers/ajax.php, images/opencast-courseware.svg, javascripts/embed.js, lib/BlockTypes/OpencastBlock.json, lib/BlockTypes/OpencastBlock.php, lib/FakeCoursewareInterface.php, package-lock.json, package.json, src/courseware-plugin-opencast-video.vue, src/register.js, stylesheets/oc.less, webpack-courseware.config.js, webpack.config.js
=> Courseware block for Stud.IP >=5.0

src/courseware-plugin-opencast-video.vue
This PR fixes #546 and **IT IS IMPORTANT** for this PR to be merged after the issue https://gitlab.studip.de/studip/studip/-/issues/274 from the main courseware to be solved and merged!
Please follow https://gitlab.studip.de/studip/studip/-/merge_requests/297
=> courseware selects as drop-up menu, fixes #546

classes/OCRestClient/ApiEventsClient.php, classes/lti/OpencastLTI.php, controllers/course.php, models/OCCourseModel.class.php, package-lock.json, package.json, plugin.manifest, views/course/index.php
=> Bugfix episodes

classes/OCRestClient/ApiEventsClient.php
=> Merge search apievents

classes/OCRestClient/ApiEventsClient.php, controllers/ajax.php, javascripts/embed.js, src/courseware-plugin-opencast-video.vue
=> Ticket 566

OpenCast.class.php
=> markupOpencast - #581

models/OCSeriesModel.php
fixes #575 
the complete removal of the description should help OpenCast in general.
I don't see any benefit for an OpenCast administrator.
=> rm studip description from series

views/course/index.php
=> add absolute uri for studio return

views/course/_episode.php
=> add base uri for mail

classes/OCRestClient/ApiEventsClient.php, views/course/_episode.php, views/course/_wip_episode.php
=> Show presenter instead of creator

views/course/_episode.php
=> New oc videoeditor

classes/OCRestClient/ApiSeriesClient.php, controllers/course.php
=> OC 12 series list compatibility

bootstrap.php, cronjobs/opencast_worker.php, lib/Models/Filter.php, lib/Models/PlaylistSeminarVideos.php, lib/Models/PlaylistSeminars.php, lib/Models/VideoSeminars.php, lib/Models/Videos.php, lib/Routes/Course/CourseListPlaylist.php, vueapp/store/videos.module.js
this PR will introduce the course playlist backend together with list of all videos for the course
=> Vuetify course playlist

classes/OCRestClient/ApiEventsClient.php, classes/OCRestClient/WorkflowClient.php, controllers/course.php, views/course/_episode.php, views/course/_wip_episode.php, views/course/index.php
and remove unused code from the WorkflowClient.
Resolves  #641
=> List videos currently being processed with OC12

app/controllers/redirect.php, lib/Controller.php, lib/Models/LTI/LtiHelper.php, lib/Models/LTI/LtiLink.php, lib/Models/Videos.php, lib/Models/VideosShares.php, lib/Routes/Opencast/UserRoles.php, lib/Routes/Video/VideoSharesList.php, lib/Routes/Video/VideoSharesUpdate.php, migrations/059_add_linkshare_table.php, migrations/064_alter_linkshare_table.php, vueapp/components/Videos/Actions/VideoAccess.vue
=> Share Link v3

lib/Models/VideoSeminars.php, lib/RouteMap.php, lib/Routes/Video/VideoCopyToCourse.php, vueapp/components/Courses/CoursesSidebar.vue, vueapp/components/Videos/Actions/VideoCopyToSeminar.vue, vueapp/components/Videos/VideoCard.vue, vueapp/components/Videos/VideosList.vue, vueapp/store/videos.module.js, vueapp/views/Course.vue, vueapp/views/CoursesVideos.vue
=> Copy Course Contents

composer.lock, lib/Models/LTI/LtiHelper.php, lib/Models/Videos.php, lib/Models/VideosUserPerms.php, lib/Providers/Perm.php, lib/RouteMap.php, lib/Routes/Course/CourseConfig.php, lib/Routes/Course/CourseSetUpload.php, migrations/067_add_student_upload_config.php, vueapp/components/Courses/CoursesSidebar.vue, vueapp/components/UserCourseSelectable.vue, vueapp/store/opencast.module.js
=> Issue 683 - Studierenden erlauben, Videos in einer VA hochzuladen

lib/Routes/Playlist/PlaylistUpdate.php, lib/Routes/Video/VideoCopyToCourse.php, vueapp/components/Error.vue, vueapp/components/SearchBar.vue, vueapp/components/UserCourseSelectable.vue, vueapp/components/Videos/Actions/CaptionUpload.vue, vueapp/components/Videos/Actions/VideoAccess/ShareWithUsers.vue, vueapp/components/Videos/Actions/VideoCopyToSeminar.vue, vueapp/components/Videos/VideoCard.vue, vueapp/components/Videos/VideoUpload.vue, vueapp/components/Videos/VideosList.vue, vueapp/store/playlists.module.js
- Fix #712 
- Error wird nun auch im fokusierten Dialog angezeigt
- Error wird aber immer noch im Hintergrund angezeigt
- Fix #727 
- Aufnahmedatum wird nicht mehr gelöscht
- Fix #737 
- mkdate hatte ein falsches Format
- Fix #740 
- Zeige nur noch Kurse, die tatsächlich hinzugefügt werden können
- Fix SQL Errors
- Fix #747 
- Button wird nun ausgegraut
- Auch in anderen Dialogen behoben
- Fix  #749 
- x-Button kann jetzt immer genutzt werden
- Fix: Error unter Arbeitplatz in VideoCard downloadAllowed() -> this.playlist is null
- Wenn User als nicht root Leserecht auf ein Video hat
- Funktion schaut dann, ob die Playlist downloads erlaubt -> es gibt aber keine Playlist
- Habs behoben
=> Multiple bug fixes

assets/css/opencast.scss, vueapp/components/Config/EditServer.vue, vueapp/components/PaginationButtons.vue, vueapp/components/Playlists/PlaylistVideos.vue, vueapp/components/UserPlaylistSelectable.vue, vueapp/components/Videos/EmptyVideoCard.vue, vueapp/components/Videos/VideoCard.vue, vueapp/components/Videos/VideoUpload.vue, vueapp/components/Videos/VideosList.vue
#715 
- 4 Zoll Display als Referenz
- Generell Buttons und Texte schlanker gemacht, alles für Mobile Geräte Nutzbar gemacht
- Videokarten verändern sich dynamisch mit kleinerem Display, Inhalte bleiben jetzt erhalten
- Paginierung stellt sich bei kleinem Display um, da lässt sich nur noch vor und zurück Schalten
=> scss restyling, better usability on small displays

vueapp/components/PaginationButtons.vue
=> Show pagination buttons only if usable #774

vueapp/components/Videos/VideoCard.vue
=> Adding actionmenu for VideoCards in PlaylistVideos-list

vueapp/common/upload.service.js, vueapp/components/Videos/Actions/CaptionUpload.vue, vueapp/components/Videos/VideoUpload.vue, vueapp/components/Videos/VideosTable.vue, vueapp/store/error.module.js, vueapp/store/opencast.module.js
#756 
- Error message bei Network Error (CORS Error)
- LTI check umgeschrieben
- Zeige Error nur 1x
- Lösche Error, wenn alle LTI checks erfolgreich
- Upload von Dateien funktioniert deshalb auch nicht
- Zeige Fehlermeldung, wenn dies der Fall ist
=> Show error messages on network errors

lib/Models/Filter.php, lib/Models/PlaylistSeminars.php, lib/Models/Videos.php, lib/RouteMap.php, lib/Routes/Course/CourseListForPlaylistVideos.php, lib/Routes/Course/CourseListForUserVideos.php, vueapp/components/SearchBar.vue, vueapp/store/videos.module.js
Changes:
- Add filter by course and by lecturer to search bar
Please check whether the SQL queries work as expected.
Closes #664
=> Search filter for courses and lecturers

OpenCast.class.php, app/controllers/course.php, lib/Models/PlaylistVideos.php, lib/Models/Videos.php, migrations/079_add_playlist_video_dates.php
Changes:
- Add mkdate and chdate to table playist video to track new added videos
- When new videos are added to a course or a video is changed, the video icon is highlighted and the number of new videos is displayed in my courses.
=> Show number of new videos in my courses

vueapp/components/Playlists/PlaylistCard.vue, vueapp/components/Videos/VideoRow.vue
Changes based on https://github.com/elan-ev/studip-opencast-plugin/issues/769#issuecomment-1714113380.
=> Change icon for linking video and playlist

lib/Routes/Video/VideoAddToPlaylist.php
Uniforms the success and error messages for adding videos to playlists.
Related to #798
=> Uniform messages for add video to playlist

lib/Models/Config.php, lib/Models/Workflow.php, lib/Routes/Config/SimpleConfigList.php, migrations/082_add_workflow_settings.php, vueapp/components/Config/EditServer.vue, vueapp/components/Config/UploadOptions.vue, vueapp/components/Videos/VideoUpload.vue
The file types for the upload can be defined in the opencast admin settings for each workflow.
UI:
Close #558
=> Configurable list of upload file types

vueapp/components/Videos/VideosTable.vue
Requested in https://github.com/elan-ev/studip-opencast-plugin/issues/664#issuecomment-1827773894.
=> Hide video filters for courses and lecturers in course playlists

vueapp/components/Courses/CoursesSidebar.vue, vueapp/components/Videos/VideosSidebar.vue, vueapp/store/config.module.js, vueapp/store/opencast.module.js, vueapp/views/Contents.vue, vueapp/views/Course.vue
#678 
- Kursübersicht
- Zeige Warning: "Die Kurskonfiguration konnte nicht vollständig abgerufen werden, daher ist das Hochladen von Videos momentan nicht möglich."
- Blende Medienupload und Medienaufnahme aus
- Arbeitsplatz
- Zeige Warning: "Die Nutzerkonfiguration konnte nicht vollständig abgerufen werden, daher ist das Hochladen von Videos momentan nicht möglich."
- Blende Medienupload und Medienaufnahme aus
=> On missing series - hide upload and show warning

assets/css/courseware.scss, courseware/vueapp/components/CoursewareSearchBar.vue, courseware/vueapp/components/CoursewareVideoTable.vue, courseware/vueapp/components/VideoRow.vue, courseware/vueapp/courseware-plugin-opencast-video.vue
#741 
- Ausgewähltes Video wird gehilighted
- Ein Scrollen bei Videoauswahl konnte ich nicht feststellen - Bei mir springt es nirgendwo hin
- Live Suche eingebaut
- Input für Suche hatte nicht die ganze Breite eingenommen - gefixt
- Fehlermeldung für LTI Fehler
=> CW-Plugin: Highlight selected item, automatic search and lti fail message

vueapp/components/Videos/VideoRow.vue
=> Add text on title for running video

lib/Models/PlaylistSeminars.php, lib/Models/Playlists.php, lib/Models/Tags.php, lib/Models/Videos.php, lib/RouteMap.php, lib/Routes/Course/CourseVideoList.php, lib/Routes/Playlist/Authority.php, lib/Routes/Tags/TagListForCourseVideos.php, vueapp/components/Playlists/PlaylistAddToCourseDialog.vue, vueapp/components/Playlists/PlaylistAddVideos.vue, vueapp/components/UserCourseSelectable.vue, vueapp/components/Videos/Actions/VideoCopyToSeminar.vue, vueapp/components/Videos/VideosAddFromCourses.vue, vueapp/components/Videos/VideosTable.vue, vueapp/store/videos.module.js
Changes:
- New option "Meine Veranstaltungen" in add videos dialog
- Allow adding videos to playlist when user is tutor in a course using this playlist
Dialog:
=> Add videos from other courses to the course, close #761

vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
=> Fix reference error in Verknüpfte Kurse

courseware/vueapp/components/LtiAuth.vue, courseware/vueapp/components/VideoRow.vue, courseware/vueapp/courseware-plugin-opencast-video.vue
#741 
- Konnte ich mit meinem Testsystem nicht richtig testen (denke aber, es funktioniert)
- Video kann nicht mehr über die VideoCard aufgerufen werden -> wird darüber nur noch selected und dann im oberen Bereich angezeigt
=> Fix currectVideo and dont play Video via VideoCard

vueapp/components/Videos/Actions/CaptionUpload.vue
Changes to add icon
Close #773
=> Change icon of subtitle file select button

vueapp/components/Videos/VideoRow.vue, vueapp/components/Videos/VideosTable.vue
Implements suggestions in #884.
Changes;
- Remove playlist action "Zum Löschen markieren" in course
- Remove video action  "Zum Löschen markieren" in course
- Show video action "Aus Wiedergabeliste entfernen" at the bottom of the action menu
- Only allow video deletions in user contents
Close #884
=> Remove delete action for videos in courses, 

vueapp/common/upload.service.js, vueapp/components/Videos/VideoUpload.vue
Remove the need of admin rights on OPENCAST server when a video is uploaded.
Close #910
=> Remove admin rights in acl on upload

vueapp/components/Videos/VideoUpload.vue
=> Show correct time in upload dialog

lib/Routes/Course/CourseAddPlaylist.php, vueapp/components/Playlists/PlaylistsLinkCard.vue
This PR fixes #923,
refer to issue's description
- passing cid to the link card component
- make sure members of the course with min.tutor permission could change the default playlist.
=> Problem with Default Playlist change in a course

vueapp/components/Playlists/PlaylistAddNewCard.vue
=> Prevent reloading site when adding playlist

lib/Middlewares/AdminPerms.php, lib/Middlewares/TokenAuthentication.php
=> Migrate middlewares from Slim v3 to v4

vueapp/components/Config/EditServer.vue, vueapp/components/Config/UploadOptions.vue
Ref #947 
Eingabe vom file type optional, wird beim leer lassen auf den default Wert gesetzt
=> Optional upload file type in ServerCard

migrations/050_new_scheme_and_cronjobs.php, migrations/080_add_playlist_video_dates.php, package.json
=> Fix migrations from v2 to v3

cronjobs/opencast_sync_acls.php, lib/Helpers/PlaylistMigration.php, lib/Models/Helpers.php, lib/Models/Playlists.php, lib/Models/REST/SeriesClient.php, lib/Models/REST/ServicesClient.php, lib/Models/SeminarSeries.php, lib/Models/Videos.php, lib/Routes/Opencast/UserRoles.php, migrations/094_add_acl_cronjob.php
=> Set acls for videos, playlists and series

lib/Routes/Config/ConfigList.php
=> Add check if server configs exist

migrations/082_add_workflow_settings.php, vueapp/components/Config/EditServer.vue
=> Fix default value error

constants.php, controllers/redirect.php
Use the redirect service for video urls as suggested in #1004
Fix #1004
=> Fix possibly invalid player url (#1004)

vueapp/components/Courses/CoursesSidebar.vue, vueapp/components/Videos/VideosSidebar.vue
=> Make sure admin setting is applied to de/activate Studio

lib/Models/Helpers.php, lib/Providers/Perm.php, package-lock.json
=> Fix media-roles and course copy

OpenCast.class.php, assets/css/opencast.scss, lib/Models/Playlists.php, lib/Models/REST/RestClient.php, lib/Models/SeminarSeries.php, lib/Routes/Playlist/PlaylistShow.php, vueapp/components/Courses/CoursesSidebar.vue, vueapp/components/Videos/VideosTable.vue, vueapp/store/opencast.module.js
- The plugin does not access opencast services when creating Tab- or Icon-navigation
- Some functions are disabled, if opencast is not available
=> Do not block Stud.IP when opencast is unavailable, fixes #1021

assets/css/opencast.scss
=> Fix views icon style

tools/ansible-testsystem/studip-demo/roles/cleaner/templates/oc.sql
=> Ansible: Set correct id in workflow config

courseware/vueapp/components/VideoRow.vue
Fixes access to undefined perms attribute of event
=> Fix missing videos with read perm in cw block

bootstrap.php, cronjobs/opencast_worker.php, lib/Models/Helpers.php
=> Show notification when video is ready

vueapp/components/Videos/VideoUpload.vue
=> Prevent mixing of mp4 and webm

OpencastV3.class.php, app/controllers/redirect.php, lib/Models/Videos.php, lib/Routes/Playlist/PlaylistRemoveVideos.php, package-lock.json, vueapp/components/Videos/Actions/CaptionUpload.vue, vueapp/components/Videos/Actions/VideoAccess.vue, vueapp/components/Videos/Actions/VideoCut.vue, vueapp/components/Videos/Actions/VideoDownload.vue, vueapp/components/Videos/VideosTable.vue, vueapp/store/playlists.module.js, vueapp/templates/admin_index.php, vueapp/templates/contents_index.php, vueapp/templates/course_index.php
fixes #1140 
fixes #816 as well
OP#37
=> Allow downloading of media files

lib/Models/Helpers.php
=> Fix `Integrity constraint violation` when adding videos to courses without playlist via cronjob

lib/Routes/Video/VideoSharesList.php, lib/Routes/Video/VideoSharesUpdate.php, vueapp/components/Videos/Actions/VideoAccess.vue
=> Allow Stud.IP internal sharing, even if global sharing is disabled

courseware/vueapp/components/VideoRow.vue, cronjobs/opencast_discover_videos.php, cronjobs/opencast_worker.php, lib/Models/PlaylistVideos.php, lib/Models/Playlists.php, lib/Models/Videos.php, lib/Routes/Playlist/PlaylistAddVideos.php, lib/Routes/Playlist/PlaylistRemoveVideos.php, migrations/099_add_playlist_availability.php, tests/VideoCest.php, vueapp/components/Videos/VideoRow.vue
=> Update video acls in oc when adding to new course

tools/pre_migrate_acls.php
Use the current AND the upcoming style for ACLs in Opencast in the pre migration script
refs #1123
=> get events paginated, use new role-based episode perms

lib/Models/Playlists.php, lib/Models/Videos.php, lib/Routes/Playlist/PlaylistAddVideos.php, lib/Routes/Playlist/PlaylistRemoveVideos.php, migrations/099_add_playlist_availability.php
=> Add videos added to a playlist in Stud.IP to OC as well when added by cronjob

lib/Models/Videos.php
=> Fix broken text filter in videos table

lib/Models/Videos.php, lib/Providers/OpencastConstants.php, lib/Routes/Video/VideoReport.php, lib/Routes/Video/VideoSharesList.php, lib/Routes/Video/VideoSharesUpdate.php, migrations/097_update_sharing_option.php, migrations/101_config_options_features.php, vueapp/components/Config/GlobalOptions.vue, vueapp/components/Videos/Actions/VideoAccess.vue, vueapp/components/Videos/VideoRow.vue
=> Add separate config options for sharing, public sharing and technical feedback

vueapp/components/Config/EditServer.vue
=> Remove broken lti check

cronjobs/opencast_discover_videos.php
We noticed that this cronjob was slow on our test system. The main bottleneck lies in the first video sync task check, as we only migrated a few OC videos and the remaining videos has no preview entry in the database. Therefore, the check is performed on 52994 videos. This patch solves this non-critical problem as it should not exist in the production setup.
=> Speed up video sync exist check in discover cronjob

migrations/051_new_scheme_and_cronjobs.php
=> Fix faulty cronjob entries from v2

app/controllers/redirect.php, lib/Models/Playlists.php, lib/Models/Tags.php, lib/Models/Videos.php, lib/Routes/Course/CourseAddPlaylist.php, lib/Routes/Playlist/Authority.php, lib/Routes/Playlist/PlaylistAddVideos.php, lib/Routes/Playlist/PlaylistRemoveVideos.php, lib/Routes/Video/VideoDelete.php, lib/Routes/Video/VideoReport.php, lib/Routes/Video/VideoRestore.php, lib/Routes/Video/VideoSharesList.php, lib/Routes/Video/VideoSharesUpdate.php, lib/Routes/Video/VideoShow.php, lib/Routes/Video/VideoUpdate.php, vueapp/components/Videos/VideoRow.vue, vueapp/store/videos.module.js
Implements the suggestions of #1222 and refactores the video perm checks. 
Close #1222
=> Fixes and updates the perms

courseware/vueapp/courseware-plugin-opencast-video.vue
I don't know why these code lines were commented out?
Fix #1201
=> Courseware: Reset paging when searching for or sorting videos

lib/Models/Playlists.php
Needs to be discussed.
Close #664
=> Show playlists from user's courses in copy dialog and in video filter

migrations/096_fix_v3.php
=> Only clear relevant caches

courseware/vueapp/components/VideoRow.vue, vueapp/components/Courses/CoursesSidebar.vue, vueapp/components/Videos/Actions/VideoAccess.vue, vueapp/components/Videos/VideoRow.vue, vueapp/components/Videos/VideosSidebar.vue
Add keyboard support for the main actions, e.g. opening a video. This PR doesn't adress all keyboard support problems.
Ref #1235
=> Add keyboard support for the common actions

cronjobs/opencast_refresh_scheduling.php
=> Only check future scheduled recordings to prevent deleting old recorded events

cronjobs/opencast_worker.php, migrations/100_migrate_missing_cw_blocks.php
=> Make sure video tokens exist whem migrating courseware

lib/Models/REST/IngestClient.php
=> Fix scheduling for devices with capabilities

assets/css/opencast.scss, lib/Models/Videos.php, vueapp/components/Videos/VideoRow.vue
=> Correctly consider global default visibility of videos

lib/Models/REST/SeriesClient.php, lib/Models/ScheduleHelper.php
=> prevent php warnings, fixes #1308

lib/Models/Config.php, lib/Models/REST/ServicesClient.php, lib/RouteMap.php, lib/Routes/Config/ConfigEdit.php, lib/Routes/Config/ConfigSetActivation.php, vueapp/components/Config/ServerCard.vue, vueapp/store/config.module.js
=> Correcting the server url fails

lib/Routes/Opencast/UserRoles.php
=> List correct institutes for admin, only list course with enabled opencast plugin

lib/Routes/Video/VideoWorldwideShareUpdate.php, vueapp/components/Videos/Actions/VideoAccess.vue
=> Fix notification bugs in "Video freigeben" dialog

app/controllers/redirect.php
=> Fix exception in cw block when video is missing

lib/Routes/Opencast/UserRoles.php
Changes:
- Deliver only required user roles based on oc config setting `episode_id_role_access`
- Fix empty or broken playlist roles if playlists are not migrated to opencast
There are definitely more potential cases to reduce the amount of user roles.
Related to #1339
=> Reduce user roles to pevent errors in Opencast

cronjobs/opencast_courseware_block_copy_mapping.php, lib/BlockTypes/OpencastBlockV3.php
Fixes in block copy mapping.:
- Map token to video id
- Fix payload clean up
- Add course exist check for workplace copy to fix foreign key contraint
=> Fix cw block copy mapping

lib/Models/Tags.php, lib/Providers/Perm.php, lib/Routes/Course/CourseConfig.php, lib/Routes/Course/CourseListForPlaylistVideos.php, lib/Routes/Course/CourseSetUpload.php, lib/Routes/Playlist/Authority.php, lib/Routes/Playlist/PlaylistAddToCourse.php, lib/Routes/Playlist/PlaylistCopy.php, lib/Routes/Playlist/PlaylistVideoList.php, lib/Routes/Tags/TagListForPlaylistVideos.php, vueapp/components/Playlists/PlaylistAddVideos.vue, vueapp/components/Videos/VideoRow.vue, vueapp/components/Videos/VideosTable.vue, vueapp/views/Course.vue
This PR refs https://github.com/elan-ev/studip-opencast-plugin/issues/1218,
There are some places left to check, these will follow in the future
=> Fix and review for the hardcoded permission checks in API Routes and UI

composer.json, composer.lock
Fixes #https://github.com/elan-ev/opencast-php-library/issues/47
=> Update elan-ev/opencast-api to 1.9.1

lib/Routes/Video/VideoWorldwideShareUpdate.php, vueapp/components/Videos/Actions/VideoAccess.vue, vueapp/components/Videos/VideoRow.vue
This PR fixes #1307,
It contains some improvements in terms of proper error handling and info, as well as checking specifically for running videos in order to prevent users to access the video visibility change dialog and endpoints!
=> Enhance video public sharing functionality

.github/workflows/run-tests.yml
Curl responds with code 0 if the response returns for example a 404 error. This change should fix this.
=> Tests: Fail curl command on error

assets/css/opencast.scss, vueapp/components/Videos/Actions/VideoAccess.vue, vueapp/components/Videos/Actions/VideoEmbeddingCode.vue, vueapp/components/Videos/VideoRow.vue
This PR is based on https://github.com/elan-ev/studip-opencast-plugin/pull/1365, with optimized UI and a11y.
=> Add embedding link

lib/Models/REST/Config.php
=> Add check for services in maintenance mode

cronjobs/opencast_sync_acls.php
Fixes the high memory consumption in the sync acls cronjob based on the changes in https://github.com/elan-ev/studip-opencast-plugin/pull/1265
=> Fix memory limit overflow in sync acls cronjob

vueapp/components/Config/EditServer.vue, vueapp/components/Config/ServerCard.vue
=> validate opencast version number
