elan-ev/studip-opencast-plugin

- plugin.manifest
This patch switches to HTTPS as protocol for linking the plugin's
homepage.
> Use HTTPS in homepage link

- controllers/course.php
- views/course/_episodelist.php
- views/course/index.php
Dieser Patch korrigiert das Zeitformat welches momentan
`<Stunde>:<Monat>` dargestellt hat.
This fixes #79
> Korrektur des Zeitformats

- views/course/index.php
Dieser Patch ändert die Aktionslinks für Sichtbarkeit, so dass sie
keinen Status sondern eine Aktion beschreiben.
This fixes #78
> Beschreibung der Sichtbarkeitsaktionen

- controllers/course.php
This patch fixes a few typos in the message which pops up after a file
has successfully been uploaded to Opencast.
> Fixed typo in upload dialog

- models/OCCourseModel.class.php
The unit for the sampling rate (kHz) was used to describe the bitrate
which lead to incorrect (and confusingly high) sampling rates to be
displayed.
> Use correct unit for bitrate

- OpenCast.class.php
- models/OCSeriesModel.php
If the series metadata are empty, users get a warning since the plugin
tries to iterate over a boolean value:
Warning: Invalid argument supplied for foreach() in
/var/www/studip/public/plugins_packages/elan-ev/OpenCast/controllers/course.php
on line 147
This patch ensures to return an empty array instead of false if there
are no data.
*Note that I did not test the patch in action.*
> Error when series metadata are empty

- README.md
This is useful if you see Markdown converted to HTML, like on GitHub
> Link the INSTALL.md

- classes/OCJob.php
Otherwise Opencast says it's READY for more chunks while Stud.IP is waiting to get a COMPLETE status by Opencast. This is either running until your Opencast server dies, PHP max execution time is hit or any database server involved quits the connection.
> Return number_of_chunks not is_infinite()

- models/OCCourseModel.class.php
Ogg should can offered for download if available. Also add MIME-Minor-Type to download dialog.
Additionally, you should always check there is audio. mpeg might be also just a container for something else.
> Bugfix: No free audio format offered for download

- views/course/_episode.php
Wie mit Nico abgesprochen, sollen Lehrende trotz systemweiten Verbots Medien downloaden dürfen. siehe Kommentar an #184
> always allow download for lecturers, refs #184

- controllers/ajax.php
- models/OCSeriesModel.php
1. MariaDB requires unambiguous column names even if the values are
guaranteed to be the same.
2. The script (embed.js) requires the response to be a JSON array,
not a JSON object.
3. Fixes inefficient SQL query for root user where table that was
never referenced had been joined.
Resolves #230
> Fix: Editor video insertion button

- classes/OCRestClient/WorkflowClient.php
- CURL_INIT is never called
- Behebt: Lehrende können Daten fehlgeschlagener Events nicht löschen (Fehlermeldung: "Die hochgeladenen Daten konnten nicht gelöscht werden.")
> Fix WorkflowClient::removeInstanceComplete

- controllers/course.php
- migrations/029_add_course_config_for_mediadownload.php
- views/course/_episode.php
- views/course/index.php
Während zuvor nur ein systemweites Verhindern der Downloads möglich war, darf jede*r Lehrende nun selbst entscheiden, ob er/sie Downloads verhindern möchte.
> Add course specific config to prevent downloads, refs #184

- views/course/index.php
> Weglassen von `workflowID` aus Studio-Link

- controllers/course.php
In [views/course/index.php#L115](https://github.com/elan-ev/studip-opencast-plugin/blob/master/views/course/index.php#L115) course administration links are shown if user is at least `tutor`, however the controller action for allow/disallow downloads checked for `dozent`.
A statement from our Stud.IP administration:
> Tutoren können alles was Lehrende können in der Veranstaltung. Sie können nur nicht selber Veranstaltungen anlegen. Es sind auch nicht immer Studierende die Tutoren sind, manchmal auch Mitarbeiter.
Another statement from elearning dept seems to emphasize that:
> Ich denke [...] an [...] hilfsbedürftige Lehrende, die sich von dem/der TutorIn [...] abnehmen lassen und wäre daher eher für erlauben.
> "Mediendownload verbiteten" schon für Tutoren

- javascripts/application.js
Sending user input through an XML serializer is not enough;
some characters, which are not allowed in XML are still present,
for instance the vertical tab character.
See for instance: https://stackoverflow.com/q/14665288/2683737
or: https://github.com/sparklemotion/nokogiri/issues/1581#issuecomment-272455205
or: https://www.w3.org/TR/xml11/#sec-starttags
In Opencast, the vertical tab 0x0b causes events with almost
entirely blank meta data shown in Admin UI.
https://github.com/opencast/opencast/issues/2127
This should not notably impact performance, as usually only small strings are processed and Emoji will be mostly untouched.
> Remove invalid XML characters

- models/OCModel.php
Apply Stud.IP-generated ACLs to new episodes in Opencast right
after they have been detected and a reference has been stored
in the Stud.IP database.
In commit 2a08fcde8 we forgot setting ACLs right after storing
detected episodes in the database.
This was probably the cause why some of our Opencast Studio
users reported missing permissions on their produced episodes
right after Opencast published them.
----
The bottom line is the ACL logic is so complicated that I might
miss a point. When I have the time, I'll probably build a chart of
the desired behavior and compare that to the current one.
> Apply ACLs to new episodes after storing in DB

- OpenCast.class.php
- Einstellungsmöglichkeit wird aus Einrichtungen komplett entfernt
- Bei Studiengruppen hat nur noch root Einstellungsmöglichkeiten
TODO:
Einstellungsmöglichkeit wird nur ausgeblendet, falls das Plugin deaktiviert ist!
Studenten können das Plugin also immer noch in einer Studiengruppe deaktivieren, falls es aktiviert ist.
> Ausblenden aus Studiengruppe und institut #410 #412

- views/course/index.php
#406 
Meldung wird oben auf der Seite als Fehler angezeigt.
Wenn Fehler, ist "Hochladen durch Studierende erlauben" ausgeblendet (deaktivieren geht noch)
> Hochladen für Studierende erfordert Freischaltung des Opencast Inhaltselements

- views/course/_episode.php
Unsere Stud.IP Support SHK schrieb: "Hallo nochmal, wollte nur Be-
scheid geben, dass immer noch viele die Feedback-Funktion im Opencast
Reiter benutzen um ihren Dozenten Feedback zur Aufzeichnung zu geben.
Muss die Tickets dann immer an die Dozenten weiterleiten. Könnte man
das evtl. irgendwo klarer kennzeichnen, dass die Nachrichten bei uns
ankommen und nicht bei den gewünschten Dozenten? 😅 Liebe Grüße"
> Knopf "Technisches Feedback" nennen

- controllers/course.php
Wenn ein Dozent oder Tutor sein Einverständnis zurück zieht, sollte auch nur sein Einverständnis gelöscht werden. Kann zwar sein, dass dann noch immer Vorlesungen von ihm da rumliegen, aber dann muss er sie halt vorher löschen.
> Withdraw TOS only for the user who did

- controllers/course.php
Wenn Tutoren auch Planen und Hochladen können, müssen sie auch die Nutzungsbedienungen/TOS/Datenschutz akzeptieren oder wenigstens lesen.
> Tutors must provide TOS consent, too

- views/course/index.php
Admins können keine Nutzungsbedingungen akzeptieren. Folglich sollten sie auch den Link zum Zurückziehen, der einfach nichts tut auch nicht sehen.
> Hide withdraw consent for admins

- controllers/course.php
Zwischen dem Eintrag als Leser*innen und dem Nichtsehen der Videos besteht ein kausaler Zusammenhang,
der mit diesem Commit verdeutlicht wird.
"Eventuell" gestrichen. Wen es stört, der weiß, an wen er sich nun wenden kann und alle anderen werden wegen
dieses Textes nicht anfangen ihren Lehrenden zu schreiben.
Bitte.
> Info für Leser*innen: Kausalzusammenhang

- cronjobs/refresh_scheduled_events.php
ApiEventsClient::getAllScheduledEvents() has no parameters.
Please carefully review and test this. Thank you.
> No params on ApiEventsCl::getAllScheduledEvents()

- controllers/admin.php
- views/admin/_ca-selection.php
- views/admin/_config_boolean.php
- views/admin/_config_integer.php
- views/admin/_config_string.php
- views/admin/_endpointoverview.php
- views/admin/_initial_config.php
- views/admin/resources.php
- views/course/_download.php
- views/course/_schedule.php
- views/course/config.php
- views/course/workflow.php
#511 
- Wird wohl über js gehändelt (javascripts/embed.js)
- Bei meinem Localsystem und dem Testsystem hat die Suche nicht funktioniert, konnte es daher nicht testen
- Wird nicht genutzt, hab ich entfernt
- Konnte ich nicht reproduzieren
-  Der Name wird in einem Textfeld gefiltert angezeigt. Da konnte ich kein XSS anwenden
> fix XSS vulnerability

- constants.php
- views/course/upload.php
It seems to me that since upload via studip is gone, chunked upload was also removed, [in spite of Opencast supporting that, too](https://stable.opencast.org/docs.html?path=/upload). Since still supported by the backend and occasional issues with people with slow connections, it might be worth implementing and I leave the settings in place.
> Remove note about chunk size

- classes/lti/OpencastLTI.php
ACLs should be changeable even if the previous workflow
was stopped or failed. Since the Stud.IP Opencast plugin
decided to remove failed workflows from view of the lecutror
it isn't obvious to them why they can't change ALCs.
> Allow ACL changes on stopped, failed WFIs

- controllers/course.php
- models/OCEndpoints.php
An welcher Stelle und für wen soll die Fehlermeldung angezeigt werden? 
Jetzt wird sie jedem angezeigt, wer eine Episode löschen möchte - relevant wäre es ja nur für Admins?
ggf. könnte man den Endpoint auch automatisch hinzufügen
> admin-ngevent troubleshooting

- controllers/ajax.php
- controllers/course.php
- javascripts/application.js
- migrations/046_add_remove_media.php
- Since media upload targets the Opencast Admin Server, failed upload logging won't throw any error message
- Logging is useful especially for study group uploads; if a student claims having uploaded something that might have been deleted by someone else
- Upload log can be faked the way it's implemented; a forgery-proof implementation would check stud.ip-side if the media package indeed has been recently created by the current user. But since the user name can't be forged, the risk of that simpler implementation appears to be low enough. Anonymous users get a 403: "message: Sie haben nicht die Berechtigung, diese Aktion auszuführen bzw. diesen Teil des Systems zu betreten."
> Log media upload and episode deletion

- OpenCast.class.php
Icon in der Veranstaltungsübersicht nicht anzeigen, wenn noch keine Serienverknüpfung da ist.
Resolves #577
> Hide OC icon in course overview if no series set

- javascripts/application.js
- views/course/_schedule.php
- views/course/index.php
The most common way our lecturers caused trouble is by repeatedly
clicking the schedule button and the "create new series" link.
Addresses #587
> Prevent duplicate scheduling and series creation

- controllers/admin.php
- migrations/047_add_upload_legal_info_conf.php
- views/admin/_initial_config.php
- views/course/upload.php
- Lawyers assessment appears to vary on every university
- 2 new config variables:
- OPENCAST_UPLOAD_INFO_TEXT_HEADING,
- OPENCAST_UPLOAD_INFO_TEXT_BODY
Before:
With PR:
> Allow custom info message texts on upload page

- views/course/index.php
Changing visibility takes some time (as Opencast has to publish
changed ACLs to the search index for the change to become
effective).
Some users, however expect their changes to be applied immediately.
Before:
This PR:
> Add hint to visibility change dialog

- composer.json
- composer.lock
- lib/Models/REST/RestClient.php
With this PR a newer version of elan-ev/opencast-api is in place, that contains the renaming of the main class to `Opencast`
**NOTE**: composer update is required after the composer.json is in place
> upgrade elan-ev/opencast-api to 1.2.0

- classes/OCRestClient/ApiEventsClient.php
- views/course/_download.php
- allow download presentation audio
- correctly calculate sizes of files offered for download
- use more images as preview fallback images
- display supplemental material for download:
- BBB sends shared notes (which then can be imported into an Etherpad and work can continue there) to OC
- BBB sends slides to OC
- Subtitles can be downloaded, too
**Breaking changes**:
- **allow downloading no matter which Tag**
- **drop AVI format for download (who is still using that??)**
Before this change:
After this change:
> Allow downloading supplemental material, remove tag filter, drop AVI format download

- views/course/_episode.php
Die Anzeige Wiedergabedauer/Spiellänge/duration/length eines Videos ist
dann besonders nützlich, wenn ein Kurs viele unterschiedlich lange
Videos anbietet.
Vorher:
Danach:
Resolves #509
> Show video duration in course video list

- views/course/_schedule.php
- views/course/config.php
The schedule-delay made our users press reload which caused duplicate scheduled events. Also, adding series to courses can take a considerable amount of time.
> Ask user to wait when connecting series and mass schedule

- views/course/upload.php
- "Aufzeichnung der Votragsfolien"
Nobody gets this right. Some try to upload PPTs and PDFs directly,
others simply skip this. So we relabel this to "Screencast"
- "Aufzeichnung des Votragenden"
Ends up as the default option for most screencasts as lecturors
think if their voice is in, it's the correct option.
Clarify that this option is for camera recordings of non-textual
content.
- Move the screencast option to the first place as most uploads
are actually screencasts (presentation + voice)
Before:
With this PR:
> Relabel upload video options

- controllers/course.php
- stylesheets/oc.less
- views/course/_episode.php
Our Opencast workflows now first create an engage publication very quickly with only a limited set of features and later create the preview/internal publication for the Opencast editor.
However after creating the engage publication, episode data is cached for about 24h and our lecturors are looking for the cutting button.
This PR adds a "Metdaten aktualisieren" button which will purge/ expire the cached data.
> Add episode refresh button (to purge cache)

- classes/OCRestClient/SchedulerClient.php
Events can be shortened by a slider in the UI. However, for this to work, the Scheduler Client also has to accept these shorter times.
See
https://github.com/elan-ev/studip-opencast-plugin/commit/0508390ad8981abab8869557c425e2dc7825ae12#r96509687
> Allow scheduled events to be shorter than lecture

- assets/css/opencast.scss
- lib/Models/Videos.php
- lib/RouteMap.php
- lib/Routes/Opencast/UserRoles.php
- lib/Routes/Playlist/PlaylistVideoList.php
- lib/Routes/Video/VideoUpdate.php
- migrations/066_add_visible_timestamp.php
- vueapp/components/Videos/Actions/VideoEdit.vue
- vueapp/components/Videos/VideosList.vue
When calling the database via the "PlaylistVideoList" route, videos are now filtered according to their visibility on a course-specific basis.
- Dozents and higher perms see all videos.
- Default visibility is the one of the playlist (oc_playlist_seminar).
- Custom visibility for a video in a playlist in a course (oc_playlist_seminar_video).
- Timestamping will filter out all videos with a timestamp in the future 
Configurable for every VideoCard (With VideoEdit component)
- Setting the visibility radio button to default will set the timestamp to null
- Any change on the visibility radio buttons that make the timestamp invalid will set it to null
- Any change to the timestamp will set the radio button accordingly (if invalid)
- Remove button to set timestamp input null
UserRoles are now …
> Implementation of palylist_seminar_video visibility with timestamps - #662

- lib/Models/Tags.php
- lib/RouteMap.php
- lib/Routes/Tags/TagListForPlaylistVideos.php
- lib/Routes/Tags/TagListForUserVideos.php
- vueapp/components/SearchBar.vue
- vueapp/store/videos.module.js
#696 
- Zwei neue Routen zum abrufen von Tags für alle Videos eines Nutzers und Tags für spezifische Playlists
- Nach fetch von Videos wird diese Liste entsprechend aktualisiert (im vue-store)
- In Searchbar werden damit alle Tags der verfügbaren Videos angezeigt (Je nach Ansicht)
> Fix tag selection in searchbar #696

- .github/release.yml
This patch configures the release notes which can be automatically generated by GitHub to have a better structure based on labels assigned to pull requests.
The release notes can be generated either by clicking the „generate release notes“ button when creating a new release manually, or this can be part of a workflow which completely automates cutting a release.
The generated release notes would look like this:
- https://github.com/opencast/opencast-editor/releases/tag/2022-10-06
Automating the whole release could look like this (here is just generates draft releases which still have to be approved manually):
- https://github.com/opencast/opencast-editor/blob/main/.github/workflows/create-release.yml
> Automatic Release Notes

- .github/workflows/check-label.yml
This patch adds a GitHub Actions workflow which checks that pull requests have proper labels assigned to them.
In combination with pull request #731, this ensures that pull requests are always properly listed  in the release notes.
> Enforce proper labeling of pull requests

- app/controllers/contents.php
- app/controllers/course.php
- assets/css/opencast.scss
- lib/Models/REST/ApiEventsClient.php
- lib/Models/Videos.php
- lib/RouteMap.php
- lib/Routes/Config/SimpleConfigList.php
- lib/Routes/Video/VideoCaptions.php
- vueapp/common/upload.service.js
- vueapp/components/Videos/Actions/CaptionUpload.vue
- vueapp/components/Videos/VideoCard.vue
- vueapp/components/Videos/VideoFilePreview.vue
- vueapp/components/Videos/VideoUpload.vue
- vueapp/components/Videos/VideosList.vue
- vueapp/store/videos.module.js
- vueapp/templates/contents_index.php
- vueapp/templates/course_index.php
> Add subtitle upload #355

- .github/workflows/check-merge-conflict.yml
This patch adds a GitHub Actions workflow to automatically notify pull request authors about merge conflicts by commenting at and labeling the pull request.
> Notify pull request authors about merge conflicts

- lib/Routes/Config/ConfigAddEdit.php
- migrations/074_update_config_key.php
#718
- New migration to delete service_user and service_password from oc_config key
- Route checks if a service_url already exist and throws an error message
> Fix sql duplicate service_url error

- lib/Models/Config.php
- lib/Models/Helpers.php
- lib/Routes/Config/ConfigAdd.php
- lib/Routes/Config/ConfigDelete.php
- lib/Routes/Config/ConfigEdit.php
- lib/Routes/Config/ConfigUpdate.php
- vueapp/components/Config/AdminConfigs.vue
- vueapp/components/Config/ConfigOption.vue
- vueapp/components/Config/GlobalOptions.vue
- Fixes #708 
- Uses dropdown of servers to choose from instead
- Making sure the default server is always set, calls the appropriate check in the backend to set it when:
- a new server has been added
- a server has been deleted
- the global config is stored
- ServerCard did save incorrect configurations
- Fixed it by not saving configs with errors
> Fixing server card issues

- cronjobs/opencast_discover_videos.php
- lib/Models/Videos.php
- lib/RouteMap.php
- lib/Routes/Video/VideoAdd.php
- vueapp/common/upload.service.js
- vueapp/components/Videos/VideoCard.vue
- vueapp/components/Videos/VideoUpload.vue
- vueapp/store/videos.module.js
#765
- On Mediaupload attach video to currently selected playlist
- Currently videos will also be added to the course playlist 'Kurswiedergabeliste'
- Is not implemented for video recordings via studio upload!
> On Mediaupload, attach video to currently selected playlist #765

- lib/Providers/OpencastConstants.php
- vueapp/components/Config/EditServer.vue
- vueapp/components/Config/GlobalOptions.vue
- vueapp/components/MessageBox.vue
- vueapp/components/Playlists/PlaylistAddCard.vue
- vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
- vueapp/components/Videos/Actions/CaptionUpload.vue
- vueapp/components/Videos/Actions/VideoDelete.vue
- vueapp/components/Videos/Actions/VideoDownload.vue
- vueapp/components/Videos/VideoCard.vue
- #782 
- Using download attribute doesnt work
- I implemented it with axios
- #770 
- Rename top element to "Verknüpfte Veranstaltungen" instead of just "Veranstaltung"
- #764 
- Rename Action "Entfernen" to "Zum Löschen markieren"
- Filled DeleteDialog with infos what happens with a marked Video
- #748 
- Limit input length to 255 characters
- #746 
- Messagebox is now closable
- #744 
- I cannot reproduce error
- Added a success Message
- Improved styling of the form
- Add some text telling which file format is supported
- #714 
- Rephrased server delete dialog
- Making sure the server id is a Number in globalOptions
- There was a display bug on the Testserver Admin configs (Default server config)
> Fixed multiple Issues

- cronjobs/opencast_clear_recycle_bin.php
- vueapp/components/Videos/Actions/VideoDeletePermanent.vue
- vueapp/components/Videos/VideoCard.vue
- vueapp/components/Videos/VideoUpload.vue
#760 
- State des Videos wird sofort auf 'running' gesetzt -> damit erscheint Zahnrad Symbol
- Aber nur, wenn über "Medien hochladen" hinzugefügt
- Funktioniert momentan nicht für StudIO uploads
- Wird so lange angezeigt, bis der discover_videos cronjob das Video in OC entdeckt und einen VideoSync dazu erstellt - Zahnrad Symbol bleibt also so lange, bis der worker cronjob das Video vernünftig einhängt
- Ausgeblendete Action Items:
- Bearbeiten
- Medien runterladen
- Untertitel hinzufügen
- Unwiderruflich entfernen
- Löscht auch die Daten in OC, deshalb muss man warten, bis das Video verarbeitet ist
- Blende ich nicht aus, habe dies in der Dialogbox erklärt
> Show status of videos in progress

- vueapp/components/Studip/StudipActionMenu.vue
The mixin function `getStudipConfig` of the studip core is not exposed to the plugin. I replaced it with the direct access to the global window variable.
Fixes #807 and hopefully fixes #797
> Fix missing function error in studip action menu, fixes #807

- lib/Providers/OpencastConstants.php
Entfernt die doppelte Einstellung für das Ablaufdatum von gelöschten Videos. 
Fixes #803
> Remove redundant global config option

- vueapp/components/Videos/VideoUpload.vue
- vueapp/components/Videos/VideosList.vue
- vueapp/store/videos.module.js
#760
- Bei mir werden nach Medienupload (sowohl innerhalb eines Kurses als auch im Arbeitsplatz) Videos im Bearbeitungszustand angezeigt
- Vorher musste die Seite refreshed werden, um diese zu sehen
- Habe das Laden von Videos aufgeräumt und Funktionalität eingebaut, um auch außerhalb der VideosList die Videos zu refreshen
- Damit wird nach erfolgreichem Upload das Video direkt in der Liste angezeigt
> Reload videos after upload

- vueapp/components/Videos/VideosList.vue
#789 
- Im Frontend keine Assoziation zwischen auswählbaren Videos und bereits vorhandenen Videos der Playlist
- Im backend durch Filter die Videos der Playlist aus den "auswählbaren" Videos entnehmen (Mit Paging einzige sinnvolle Lösung)
-> Mit Mehraufwand Statusflags mitgeben und Videos im Frontend ausgrauen - Ist das so bevorzugt?
-> Erstmal so umgesetzt, dass nur die Videos angezeigt werden, die auch hinzugefügt werden können
- Fehlerhafte Zählung war nur temporär im frontend
-> mit refresh wird counter immer korrekt gesetzt
- Jetzt können vorhandene Videos nicht mehr hinzugefügt werden, sollte daher kein Problem mehr sein
> Filter existing videos when adding videos to playlist

- vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
- vueapp/components/Videos/Actions/VideoRemoveFromPlaylist.vue
- vueapp/components/Videos/VideoRow.vue
- vueapp/components/Videos/VideosTable.vue
Wie in https://github.com/elan-ev/studip-opencast-plugin/issues/795#issuecomment-1752759327 beschrieben, werden die Bulk-Aktionen als Einzelaktionen rechts im Dreipunktemenü angeboten. 
Problematisch könnte sein, dass jetzt im Aktionenmenü zweimal das "trash"-Icon vorkommt. Das Icon wird für die Aktionen "Aus Wiedergabeliste entfernen" und "Zum Löschen markieren" verwendet. 
Außerdem könnte das Menü mittlerweile zu voll sein?
Closes #795
> Bulk actions as single actions

- assets/css/opencast.scss
Bei dem Versuch, die Videos auf eine Zeile mit `Overflow: hidden` anzuzeigen, gab es da einige Probleme.
Damit `Overflow: hidden` funktioniert, musste das Tabellenlayout auf [fixed](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout?retiredLocale=de#fixed) gesetzt werden, damit die Overflows überhaupt versteckt werden. Das wiederum führte dazu, dass bei der Verwendung von Colspan an den Stellen der ausgeblendeten Spalten leere Spalten angezeigt wurden. 
Aus diesen Gründen und der Einheitlichkeit zu den vorhandenen Stud.IP-Tabelle wurde die folgende Lösung implementiert:
- Die Titelgröße hat die Standardgröße, wie im Dateibereich
- Das Vorschaubild hat einen Minimalbreite von 90 Pixeln, damit das Bild nicht zu sehr gestaucht wird
- Lange Titel werden bei Overflow an beliebigen …
> Prevent overflow of videos table on small devices

- vueapp/components/MessageBox.vue
- vueapp/store/messages.module.js
- vueapp/store/playlists.module.js
Fixes:
- #798
- Benachrichtigungen können die gleiche ID erhalten, da für die ID die Anzahl der Nachrichten verwendet wird.
- #768
- Nachrichten werden beim Schließen nicht aus dem Vuex-Store entfernt
> Fix some notification problems

- vueapp/store/messages.module.js
Änderung:
- Vorhandene Error-Benachrichtigungen werden entfernt, wenn eine Success-Benachrichtigung hinzugefügt wird
Bei dieser Änderung war ich mir nicht ganz sicher, ob wir dieses Verhalten wirklich haben wollen. Hier stellt sich die Frage, ob Fehler- und Erfolgsnachrichten gleichzeitig auftreten können?
Closes #705
> Clear errors when success message is displayed

- assets/css/opencast.scss
- lib/Models/Config.php
- lib/Routes/Config/ConfigAdd.php
- lib/Routes/Config/ConfigEdit.php
- vueapp/components/Config/EditServer.vue
- vueapp/components/Config/ServerCard.vue
- vueapp/components/Config/WorkflowOptions.vue
- vueapp/store/error.module.js
- vueapp/store/opencast.module.js
#710
- Nutzerkennung/Passwort wird korrekt behandelt
- Eintragen von duplizierten URLs nicht möglich
- URLs die nicht erreichbar sind schmeißen cURL error
-> zB: cURL error 6: Could not resolve host: staging-oc-admin.uni-osnabrueck.d (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://staging-oc-admin.uni-osnabrueck.d/services/services.json
- Message wurde abgegriffen und angepasst
- LTI
- LTI kann während der Konfiguration ohne weiteres nicht behandelt werden
-> Fehlerhafte Eingaben möglich
- LTI wird nun nach der Konfiguration geprüft
- Bei Fehlschlag schließt sich Dialog nicht und zeigt Meldung an
- Bei Aufruf der Admin Seite werden alle Server periodisch überprüft (wie in der VideoTable)
- Bei Fehler wird rotes Ausrufezeichen in der Card angezeigt
- Bei klick auf die …
> Error handling on ServerCards

- lib/Models/Config.php
Das war mir aufgefallen, als ich den Workflow von "fast" zu "schedule-and-upload" umstellen wollte. 
**Hinweis**:
Bei Workflow "fast" werden in hochgeladenen Videos keine Downloads und keine Dauern angezeigt. Zumindest ist das bei mir der Fall. Eventuell könnte dieser Hinweis zukünftige Fehlersuchen erleichtern.
> Fix workflows save in server settings

- cronjobs/opencast_discover_videos.php
- lib/Models/Helpers.php
- lib/Models/Videos.php
- lib/Routes/Config/ConfigEdit.php
- lib/Routes/Config/ConfigList.php
- lib/Routes/Config/SimpleConfigList.php
- migrations/079_add_config_active.php
- vueapp/components/Config/EditServer.vue
- vueapp/components/Config/GlobalOptions.vue
- vueapp/components/Config/ServerCard.vue
#832 
- Nach Erstellung des Servers wird bei Fehlschlag der LTI Verbindung eine Warning statt einem Error geschmissen. (Gilt nicht für Verbindungstests bei Aufruf der Seite)
- Bei den Verbindungstests wurde "LTI" aus der message entfernt
- Das Icon für einen Fehlerhaften Verbindungstest ist jetzt ein tooltip
- Das tooltip ist noch buggy! Es zeigt bei meinem Testsystem eine Leere Box an, sobald es Sichtbar ist - Woran liegt das???
- ServerCards können deaktiviert werden
- Zeige Checkbox in oberer rechter Ecke (statt der id des Servers)
- Ich finde die Checkbox unschön, könnte man das auch anders machen?
- Deaktivierbarkeit führt zu:
- Nur aktivierte Server werden in default server Eingabe angezeigt
- Default Server wird bei (de)aktivierung geprüft und ggf neu gesetzt
- Videos eines …
> Warnings for Servercard and ability to disable configs

- assets/css/opencast.scss
- lib/Models/PlaylistSeminars.php
- lib/Models/Playlists.php
- lib/Models/Tags.php
- lib/Models/Videos.php
- lib/Routes/Course/CourseAddPlaylist.php
- lib/Routes/Course/CourseListForPlaylistVideos.php
- lib/Routes/Course/CourseListForUserVideos.php
- lib/Routes/Course/CourseListPlaylist.php
- lib/Routes/Playlist/PlaylistList.php
- vueapp/components/Courses/CoursesSidebar.vue
- vueapp/components/PaginationButtons.vue
- vueapp/components/Playlists/PlaylistAddCard.vue
- vueapp/components/Playlists/PlaylistAddNewCard.vue
- vueapp/components/Playlists/PlaylistAddVideos.vue
- vueapp/components/Playlists/PlaylistCard.vue
- vueapp/components/Playlists/PlaylistsLinkCard.vue
- vueapp/components/Playlists/PlaylistsTable.vue
- vueapp/components/SearchBar.vue
- vueapp/components/Videos/VideosTable.vue
- vueapp/store/playlists.module.js
- vueapp/store/videos.module.js
- vueapp/views/Playlists.vue
Changes:
- New add playlist dialog in course
- Shows playlists of work place
- Paging for playlists table
- Filter + Search for playlists
- Available filters: Tags, Courses, Lecturers
Fixes:
- [Prevent adding the same playlist to course multiple times](https://github.com/elan-ev/studip-opencast-plugin/commit/eec504137f52a175cf54e57bdf2a560a42c9af69)
- [Same tag created by different users is not filterable in videos table](https://github.com/elan-ev/studip-opencast-plugin/commit/09408ef3bf6264051a940529e82c61dc956a4dc5)
Playlists add dialog in course:
> Playlists Changes

- vueapp/components/Config/ServerCard.vue
- vueapp/store/messages.module.js
#832 
- Nutze Studip-Icon für Checkbox in ServerCard
- Meldung, ob Server aktiviert oder deaktiviert wurde
- Änderung in Messages
- Vorher: Wenn bereits existierende Message hinzugefügt wird, wird die Message ignoriert
- Bedeutet die Message bleibt einfach an der selben stelle stehen. So könnte es passieren, dass der User eine Meldung nicht wahrnimmt, wenn diese erneut auftritt und noch in der MessageList vorhanden ist
- Jetzt: Lösche die existierende Message und füge sie erneut hinzu
- So tauchen hinzugefügte Messages immer unten in der Liste auf und sind auffälliger für den User
> Use Studip-Icon for ServerCard checkbox and show incoming messages always as new ones

- vueapp/components/Config/ConfigOption.vue
- vueapp/components/Config/EditServer.vue
- vueapp/components/Playlists/PlaylistAddCard.vue
- vueapp/components/Playlists/PlaylistEditCard.vue
- vueapp/components/Videos/Actions/VideoAccess/ShareWithUsers.vue
- vueapp/components/Videos/Actions/VideoEdit.vue
#831 
- Leere Inputs werden jetzt bei den entsprechenden Formularen hervorgehoben
- Fehlerhafte Eingaben in der ServerCard (wie z.B. URL-Schema) werden im backend getriggert und sind daher nur sehr umständlich auf einzelne input-fields zurückzuführen. Daher werden diese vorerst nicht hervorgehoben
> Fehler bei leeren Inputs

- vueapp/components/UserCourseSelectable.vue
- vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
#790 
- Mit 'select' und seperater search-box nicht umsetzbar, da bei einer Suche das ausgewählte Item nicht mehr ein 'onChange' triggern kann
- Habe dafür jetzt studip-select genutzt
- Die Aufteilung in Semestern ist weiterhin eingebaut (Sieht aber nicht so schön aus wie mit 'optgroup', Semester wird einfach ausgegraut und ist nicht auswählbar)
- Hab auch noch die Suche nach Semestern mit integriert
> Instant save in VideoCopyToSeminar using studip-select

- vueapp/components/Config/EditServer.vue
- vueapp/components/Config/ServerCard.vue
- vueapp/components/MessageList.vue
- vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
- vueapp/components/Videos/Actions/CaptionUpload.vue
- vueapp/components/Videos/Actions/VideoAccess.vue
- vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
- vueapp/components/Videos/VideoUpload.vue
- vueapp/components/Videos/VideosTable.vue
- vueapp/store/messages.module.js
#833 
- Messages haben neues attribute {dialog: Boolean}
- MessageList hat neues prop {dialog: Boolean}
- Wenn dialog gesetzt, werden in MessageList nur Messages mit dialog attribute angezeigt
- Sobald eine Dialog-MessageList schließt, werden alle Dialog-Messages gelöscht
- So haben Dialoge eigene Messages und Fehlermeldungen, der Hintergrund bleibt damit sauber
- Error die im front end abgefangen werden könnten, sollten jetzt nur noch Messages vom typen 'error' schmeißen
- Die Error-Komponente ist immer noch Global! und fängt momentan nur Fehler von außerhalb ab (hier: [app.js:49](https://github.com/elan-ev/studip-opencast-plugin/blob/5050f0d8f8411897aef455404fe615bb51dacc92/vueapp/app.js#L49))
> Messages for dialogs

- migrations/084_upload_legal_info_remove_link.php
Removes the paragraph link in the upload legal info by updating the config `OPENCAST_UPLOAD_INFO_TEXT_BODY` in a migration. This overwrites manually changed info texts.
Deletion of link requested in https://github.com/elan-ev/studip-opencast-plugin/issues/799#issuecomment-1849887016.
Closes #799
> Remove link from upload legal info

- lib/Models/PlaylistSeminars.php
- vueapp/components/UserPlaylistSelectable.vue
- vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
- vueapp/store/playlists.module.js
**Important Note**:
Please merge after #893 as these changes would lead to conflicts.
Changes: 
- Show info indicator with linked courses for each playlist
- Add header with course names to playlist dropdown
Problem:
- The same playlist is listed multiple times in the dropdown if it is linked to multiple courses. This could lead to unexpected behavior in the dropdown.
- Issue #886 should solve this issue, as a playlist can then only exist in one playlist
Screenshot:
Solve #794, #792
Fix #875
> Show courses in video link to playliststs dialog

- assets/css/opencast.scss
- lib/Models/Helpers.php
- lib/Routes/Course/CourseAddPlaylist.php
- lib/Routes/Course/CourseConfig.php
- lib/Routes/Course/CourseListPlaylist.php
- lib/Routes/Playlist/PlaylistList.php
- lib/Routes/Playlist/PlaylistUpdate.php
- vueapp/components/Courses/CoursesSidebar.vue
- vueapp/components/Playlists/PlaylistAddCard.vue
- vueapp/components/Playlists/PlaylistAddNewCard.vue
- vueapp/components/Playlists/PlaylistCard.vue
- vueapp/components/Playlists/PlaylistEditCard.vue
- vueapp/components/Playlists/PlaylistsLinkCard.vue
- vueapp/components/Playlists/PlaylistsTable.vue
- vueapp/store/messages.module.js
- vueapp/store/playlists.module.js
- vueapp/views/Course.vue
- vueapp/views/CoursesVideos.vue
This PR fixes #878,
Please refer to the linked-issue.
Things to consider:
- A course must always have only one default playlist at a time.
- Teachers must create a new playlist, or link already existing one as default playlist when the course doesn't have one.
- There would be no more" Course playlist" or "Kurswiedergabeliste" in the sidebar, but a check icon with info.
- A Playlist can be assigned to many courses as default one.
- In Workspace Playlist table, those playlists that are default in courses will get an info icon with shows the courses.
- The course titles will get truncated (...) if they are too long.
- Teachers can change the default playlist of a course via the sidebar action item.
- The title of the default course playlist can now be changed.
- In case the default playlist …
> Course default playlist enhancements

- vueapp/components/Videos/Actions/CaptionUpload.vue
- vueapp/components/Videos/Actions/VideoCut.vue
- vueapp/components/Videos/Actions/VideoDelete.vue
- vueapp/components/Videos/Actions/VideoEdit.vue
- vueapp/components/Videos/Actions/VideoLinkToPlaylists.vue
- vueapp/components/Videos/Actions/VideoRestore.vue
- vueapp/components/Videos/VideoChangeWarning.vue
- vueapp/components/Videos/VideoPlaylists.vue
- vueapp/components/Videos/VideoRow.vue
- vueapp/components/Videos/VideosTable.vue
Implements the suggestion in https://github.com/elan-ev/studip-opencast-plugin/issues/885.
Changes:
- Add video change warning dialog
- Shows warning when video is in more than two playlists or the current playlist differs from the linked playlist
- No warning is shown if a video is linked with no playlists
- warning is shown before editing video, cutting video and changing video subtitles
- Show linked playlists in dialog of video actions "Zum Löschen markieren" and "Wiederherstellen"
Close #885
> Show warning with the effects of editing a video

- vueapp/components/Courses/CoursesSidebar.vue
Change the name of course sidebar action "Videos/Wiedergabelisten übertragen" to "Kursinhalte übertragen"
Related to https://github.com/elan-ev/studip-opencast-plugin/issues/879
> Wording of transfer course content action

- OpenCast.class.php
- app/controllers/course.php
- vueapp/components/Courses/CoursesSidebar.vue
This PR fixes #868,
please refer to the issue's description,
- In order for Stud.IP to render the navigation of plugins in responsive, it is required to pass them as navigation subs in `getTabNavigation` via `addSubNavigation`.
- In order for Stud.IP to render the sidebar items drawer for the plugin, it is required to add sidebars in the php side via `Sidebar` class -> `addWidget` method.
- In our case, that we use `CourseSidebar.vue` to render everything in one place, we had to delete the Stud.IP rendered sidebar widget.
- To make sure that external links perform and load required data, we had to have a more accurate procedure to handle Views in `CourseSidebar.vue` -> `handleView`
- In Responsive view: in order to toggle the sidebar upon clicks, we are using pure js (exception => there …
> Responsive Navigation items

- vueapp/components/Videos/VideosTable.vue
Show no loading animation during axios requests, e.g. during uploads.
Close #707
> Display no ghost video rows

- lib/Models/PlaylistSeminars.php
- lib/Models/Tags.php
- lib/Models/Videos.php
This PR fixes #920,
refer to issue's description
- The method `Videos::getFilteredVideoIDs()` was private, but it was called outside of the Model class, therefore, changing it to public class fixed the issue.
- The method name is `getFilteredVideoIDs` and it was always called `getFilteredVideoIds`, which was problematic and it is now fixed.
> Problem loading videos in Workspace by Admin

- vueapp/store/playlists.module.js
The sidebar shows up to 20 playlists due to pagination issues. This should be fixed.
Fix #926
> Load all playlists by default

- vueapp/components/Playlists/PlaylistCard.vue
The user should not be able to navigate to a playlist in the table as there is currently no place like the workspace to display a playlist which is not connected to the current course.
Fix https://github.com/elan-ev/studip-opencast-plugin/issues/886#issuecomment-1919392099
> Remove playlist link in playlists table

- lib/Models/Helpers.php
- lib/Models/PlaylistSeminars.php
- lib/Routes/Video/VideoCopyToCourse.php
- vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
- vueapp/store/videos.module.js
Problem:
- When transfering all contents of a course to a course without default playlist, the playlists are not displayed in the target course because no default playlist is set.
Solution:
- In the above case, set the default playlist of the source course as default playlist in target course.
In addition, unnecessary code is removed.
Fix #879
> Fix missing default playlist when transferring course contents

- lib/Models/Playlists.php
- lib/Models/Videos.php
- lib/Routes/Course/CourseVideoList.php
- lib/Routes/Playlist/PlaylistVideoList.php
- lib/Routes/Video/VideoList.php
- migrations/073_add_event_state.php
- migrations/076_add_course_date_fields_for_events.php
- migrations/081_add_config_active.php
- migrations/090_optimize_db.php
Changes based on https://github.com/elan-ev/studip-opencast-plugin/issues/927#issuecomment-1931561192
Changes:
- Refactor playlist filter function to lower komplexity
- Fix errors in some db migrations on down side
- Use collation `latin1_bin` for ids, enums and sort order
- Improve indexes
- Remove orphan rows with relations to deleted courses and set foreign keys to prevent this in the future
Solve #927
> DB Optimizations

- vueapp/components/Playlists/PlaylistAddNewCard.vue
Initially focus on title input  in "Wiedergabeliste anlegen" dialog, requested in https://github.com/elan-ev/studip-opencast-plugin/issues/864#issuecomment-1938792737.
Close #864
> Focus on title input in create playlist dialog

- lib/Routes/Course/CourseListPlaylist.php
- lib/Routes/Playlist/PlaylistCopy.php
- vueapp/components/Playlists/PlaylistAddCard.vue
- vueapp/components/Playlists/PlaylistsCopyCard.vue
- vueapp/store/playlists.module.js
Problem:
- Copy function in new courses without playlists doesn't work because no default course is set. The copied playlists will be copied but not displayed.
Solution:
- Set first copied playlist as default playlist in the course
Additional fix:
- Prevent returned playlist array with null value in `CourseListPlaylist`
Fix #886
> Show first copied playlist as default playlist

- vueapp/common/upload.service.js
- vueapp/components/Courses/CoursesSidebar.vue
- vueapp/components/Videos/VideoUpload.vue
- vueapp/store/opencast.module.js
Problem:
Currently, the processing of uploaded videos fails because the necessary roles and rights to the data are not yet available. This happens especially when the Stud.IP user provider caches the roles of the users but these have not been updated before processing.
Solution:
The role of the current LTI user will be added to the ACLs when the video is uploaded. This change means that the uploader always has read and write access to the video. Currently, this permission can not be removed in the plugin.
> Upload ACLs for LTI user

- vueapp/components/Courses/CoursesSidebar.vue
In our OC test system, we had the problem that the setting in Opencast was set to `false`, which caused permission errors in the workflows. With this change, we ensure that the default ACL is always set in Studio.
> Enforce standard ACLs for studio uploads

- vueapp/components/Videos/Actions/CaptionUpload.vue
- vueapp/components/Videos/VideoRow.vue
> Add Editor-tool link in caption dialog

- classes/lti/LtiHelper.php
- controllers/redirect.php
- models/Pager.php
- views/course/_lti.php
- views/course/index.php
- views/redirect/authenticate.php
Due to the firefox tracking prevention, LTI calls do not work if Opencast resides on another TLD. This MR tries to circumvent this by using iframes, like in V3 of the plugin.
> Port lti iframe to v2

- INSTALL.md
- app/controllers/admin.php
- app/controllers/contents.php
- app/controllers/course.php
- lib/Models/Helpers.php
- lib/Models/WorkflowConfig.php
- lib/Routes/Config/SimpleConfigList.php
- migrations/093_add_subtitles_workflow.php
- vueapp/common/upload.service.js
- vueapp/components/Config/WorkflowOptions.vue
- vueapp/components/Videos/Actions/CaptionUpload.vue
- vueapp/components/Videos/VideoUpload.vue
Ref #355 
- Workflow selection im CaptionUpload Dialog
- Tag=upload wird angezeigt, evtl ändern?
- Bei erfolgreichem upload der caption wird dann /api/workflows mit dem event_identifier und dem ausgewähltem Workflow angestoßen
- Caption wird als track mit flavour "captions/source+\<lang\>" hinzugefügt
- Beim anstoß eines workflows (fast) wird die caption in meinem Testsystem nicht übernommen
- https://github.com/opencast/opencast/issues/4407
- Dort wird gesagt, dass die Sprache über einen tag "lang:\<language\>" angegeben werden sollte
- Ist das so aktuell?
- In meinem Testsystem kann ich über "POST /{eventId}/track" keine Tags mitgeben, müsste man nochmal prüfen
> Run workflow on caption upload

- OpenCast.class.php
When using the plugin under PHP `8.3.6-0ubuntu0.24.04.1` with Stud.IP 5.4 we see the following warning on every page: **Warning**: Undefined global variable `$opencast_already_loaded` in **/data/studip/public/plugins_packages/elan-ev/OpenCast/OpenCast.class.php** on line **68**
This (HTML) warning breaks JSON and binary outputs, for instance, the dynamically loaded course list.
Our support suggested changing this line as in this PR.
> Avoid PHP Warning "Undefined global variable"

- vueapp/components/Videos/VideoUpload.vue
Fix #1046 by shallow coping playlists to prevent endless re-runs.
> Fix endless recursion in work place upload dialog

- courseware/vueapp/courseware-plugin-opencast-video.vue
- lib/Models/VideosUserPerms.php
- lib/Routes/Video/VideoSharesList.php
- vueapp/components/Courses/CoursesSidebar.vue
- vueapp/components/Playlists/PlaylistAddToCourseDialog.vue
- vueapp/components/Videos/Actions/VideoCopyToSeminar.vue
- vueapp/components/Videos/VideosSidebar.vue
The courseware block is still using the old api url to load the video. This leads to an error. These changes should solve such problems.
> Fix broken urls due to renaming

- lib/Models/Helpers.php
Currently, the role `ROLE_ANONYMOUS` will not be removed when updating the ACLs, as it is evaluated as an external OC role. With this change, this role will be touched, if the setting `OPENCAST_ALLOW_PUBLIC_SHARING` is active.
Fixes #1031
> Remove anonymous role if video visibility is changed to internal

- lib/Errors/ExceptionHandler.php
Json api error messages on our test system are not helpful, as no traceback is shown in the error log nor in the client. This change writes all PHP exceptions throwing in the JSON API to the error logs on the server.
> Log php exceptions in slim routes

- lib/Routes/Config/ConfigList.php
Add check if default config is not `-1` to prevent null errors. 
Fix #1056
> Fix null error if no default server exists

- courseware/vueapp/components/CoursewareVideoTable.vue
- courseware/vueapp/courseware-plugin-opencast-video.vue
Changes:
- Load the LTI authentication in the block content instead of in the video table
- Show opencast connection error after lti check is performed
Fix #1049
Fix #1064
> Fix courseware block

- app/controllers/redirect.php
- app/views/redirect/perform.php
Diese Änderungen verhindern das Anzeigen der Stud.IP-Seite beim Laden eines Videos, sodass der Übergang zwischen Stud.IP und Player geschmeidiger ablaufen soll.
Altes Verhalten (Dark-Theme im Browser):
[Screencast from 2024-11-05 13-35-24.webm](https://github.com/user-attachments/assets/d171e7a6-6807-4c5a-8749-8096e1e30b24)
Altes Verhalten (Light-Theme im Browser):
[Screencast from 2024-11-05 13-37-56.webm](https://github.com/user-attachments/assets/b78dda78-2735-4be8-9655-6258ebe9036a)
Neues Verhalten (Dark-Theme im Browser):
[Screencast from 2024-11-05 13-36-17.webm](https://github.com/user-attachments/assets/48b6992c-c4fa-4bfd-8b07-3632e055b4cf)
Neues Verhalten (Light-Theme im Browser):
[Screencast from 2024-11-05 13-36-56.webm](https://github.com/user-attachments/assets/baf20e9e-9769-4 …
> Disable page layout when loading the player

- cronjobs/opencast_sync_acls.php
It would probably be better to synchronise the ACLs of the latest videos first, since the old videos are rarely viewed. Especially in OC installations with several ten thousand videos, this could lead to delays until the ACLs of the recent videos are updated.
> Sync the latest events first in cronjob

- lib/Helpers/PlaylistMigration.php
I recieved an error when I tried to migrate the playlists in the opencast settings via the notification. This solved my problem.
> Skip unavailable events in playlist migration

- lib/Models/Playlists.php
The boolean value of `isset($entry->id)` is stored in the database instead of the playlist entry id from opencast.
> Save correct service entry id in database

- lib/Models/PlaylistSeminars.php
- lib/Models/Playlists.php
- lib/Routes/Playlist/PlaylistList.php
> Fix incorrect info in change course playlist dialog

- classes/lti/OpencastLTI.php
Some time ago, Till told me the Stud.IP Opencast plugin would only manage episode's ACLs relevant to Stud.IP where in fact, the plugin would remove ACLs from events granting permissions in secondary LMSes or other uses.
This approach checks if an existing Opencast ACL is managed by Stud.IP (`hex_Learner`/`hex_Instructor`/`ROLE_ADMIN`/`ROLE_ANONYMOUS`), and if not, it would add those again to the list of ACLs and check again,if the list of ACLs sent by Opencast differs from the list of ACLs to be set.
> Only touch ACLs managed by Stud.IP plugin

- lib/Models/Playlists.php
It seems incorrect to manipulate the current playlist acls by adding missing entries and removing duplicates before checking whether the current acls differ from the assumed acls. 
Or have I missed something?
> Fix incorrect playlist acl check

- lib/Models/Videos.php
- Remove duplicate course ids, if video is included in mutliple playlists of the same course
- Fix continuously increasing list of acls (e.g. course acls) by removing the unnecessary filter in addEpisodeAcl
adapted from #1044
> Fix event acl cronjob

- lib/Models/Helpers.php
Currently, ACLs of courses from which the video has been removed are ignored when filtering by Stud.IP roles. With this change, remaining course ACLs will be included in the filter result.
Fix #1061
> Filter legacy course acls

- bootstrap.php
- bootstrap_migrations.php
- cronjobs/opencast_worker.php
In the worker cronjob, add the video to the playlist first, before the video acls are checked.
Fix #1059
> Fix missing course acls in studio upload

- courseware/vueapp/components/VideoRow.vue
- courseware/vueapp/courseware-plugin-opencast-video.vue
- lib/RouteMap.php
- lib/Routes/Opencast/UserRoles.php
- lib/Routes/Video/VideoShow.php
> Allow users to watch videos in courseware blocks again

- lib/Models/Playlists.php
Fix #1090
More changes:
- Only send changed playlist data to opencast, which is possible due to https://github.com/opencast/opencast/pull/5743. This also removes the need to get the playlist from opencast.
> Update playlist in opencast when changing metadata

- app/views/redirect/perform.php
- assets/css/opencast.scss
- courseware/vueapp/components/CoursewareVideoTable.vue
- courseware/vueapp/courseware-plugin-opencast-video.vue
Changes:
- Re-add subtle loading spinner, close #1096
- Speed up video loading time by loading iFrame immediately
Unfortunately, I could not prevent displaying the Opencast login page if authentication failed:
> Courseware: Add loading spinner and speed up

- tests/VideoCest.php
- tests/_support/Helper/Api.php
Fixes the problem where the test tries to run the cronjob on the host instead of in the container. The `runCronjob` function now checks whether the Stud.IP cli command exists and executes the cronjob based on this either on the host or in the container.
> Tests: Add fixes and refactorings

- lib/Routes/Course/CourseRemovePlaylist.php
- vueapp/components/Videos/VideosTable.vue
Changes:
- Delete playlist completely from system in course instead of only removing it from course to prevent ghost playlists, close #1082
- Remove the playlist perm check, which in my opinion is not required, related #1110
> Delete course playlist completely

- lib/Routes/Opencast/UserRoles.php
These roles are supported from Opencast version 17. See details in https://docs.opencast.org/r/17.x/admin/#configuration/episode-id-roles/#episode-id-roles.
This is a very simple implementation to support this feature. It simply adds more roles to the provider.
Related #1123
> Add episode id roles to user provider

- vueapp/components/Courses/CoursesSidebar.vue
- vueapp/views/Course.vue
Some UI elements like the Stud.IP header or the table video actions are overlapping the playlist add dialog and the change course playlist dialog. This PR should fix this problem by changing the rendering location. The problem seems to be caused by the sticky position of the sidebar.
Screenshot
> Fix overlapping of playlist dialog by Stud.IP header

- vueapp/components/Courses/CoursesSidebar.vue
- vueapp/components/Playlists/PlaylistCard.vue
- vueapp/components/Playlists/PlaylistsCopyCard.vue
- vueapp/views/CoursesVideos.vue
The synchronisation of the playlist with Opencast while loading the playlist implemented in #955 was removed in #1028. So the playlist doesn't need to be loaded separately from the backend. This fixes the bug that the visibility attribute is incompatible between course playlists `oc_playlist_seminar` and playlists `oc_playlist`. Now only course playlists should be used in a course.
This fixes the error that the playlist is empty for students after the action ‘Mediendownloads erlauben’ has been activated.
> Fix broken playlist visibility

- lib/Routes/Course/CourseUpdatePlaylist.php
> Don't rename playlist to "Kurswiedergabeliste" after update

- lib/Models/SeminarSeries.php
> Fix series check during scheduling

- courseware/package.json
The directory node_modules were missing in the courseware app. This has no effects to the production builds.
> Fix node script build-dev

- assets/css/courseware.scss
- courseware/vueapp/components/CoursewareSearchBar.vue
- courseware/vueapp/courseware-plugin-opencast-video.vue
- lib/Models/Videos.php
Changes:
- In Courseware block, initially filter the videos of the course if a course exists
- In workplace, admins should see only the videos of their courses and videos with explicit permissions
- Fixed Bug: Admins could see all videos of the system due to a missing video join
- In cw block and workplace, show tutors and lecturers their videos from their courses and videos with explicit permissions
Screenshot of cw block filter:
> Show course videos in cw

- cronjobs/opencast_clear_recycle_bin.php
- lib/Models/REST/ApiEventsClient.php
- lib/Models/Videos.php
If the event in Opencast is not found, at least delete the entry in Stud.IP.
fixes #1139
> Allow deletion of faulty video entries in Stud.IP

- migrations/001_init_ocplugin.php
- migrations/002_workflow_storage.php
- migrations/008_workflow_configuration.php
- migrations/022_add_tos.php
- migrations/042_remove_oc_seminar_workflows.php
- migrations/051_new_scheme_and_cronjobs.php
- migrations/053_new_courseware_block.php
- migrations/059_add_linkshare_table.php
- migrations/061_update_workflow_tables.php
- migrations/064_alter_linkshare_table.php
- migrations/066_update_workflow_tables_two.php
- migrations/072_add_user_series.php
- migrations/075_remove_editor_workflow_config.php
- migrations/077_update_cw_block.php
- migrations/093_add_subtitles_workflow.php
Sets the char set `latin1` and collation `latin1_bin`  in the migrations based on the [migration 90](https://github.com/elan-ev/studip-opencast-plugin/blob/1102d47eb95f20782222a9e28420f3c1d83a6e06/migrations/090_optimize_db.php).
Close #1143
> Unify character sets and collations in migrations

- vueapp/views/CoursesVideos.vue
> Do not show missing default course playlist if the config is not available yet 

- INSTALL.md
- lib/Models/Config.php
- lib/Models/Videos.php
- vueapp/components/Config/EditServer.vue
Adds the "Ist rollenbasierter Zugriff per Event-ID aktiviert?" setting to disable the ACL check for event ID roles in the cronjob .
Notes:
- No OC version check is added
- User provider still sets the old and the new roles as the requested config can not be loaded in the class.
- Video uploads will still set the old ACLs to avoid adding more complexity to the code.
Close #1150
Additionally, removes an incorrect redirect in config model.
> Add server setting for role based event access

- migrations/092_add_oc_playlists.php
Now the playlists can only be migrated via the notification on the Opencast settings page.
Close #1166
> Remove oc playlist migration in db migrations

- migrations/100_migrate_missing_cw_blocks.php
Add a migration that iterates over all opencast blocks. For each block, it adds a token to the payload if no is set.  It also creates a row in `oc_video_cw_blocks' if a block has no entry there.
Fix #1152, fix #1147
> Fix payload of cw blocks and migrate blocks to oc_video_cw_blocks

- lib/Models/Helpers.php
Default playlist are not created in Opencast. This patch fixes this problem.
> Add default playlist to Opencast

- cronjobs/opencast_discover_videos.php
The "discover new videos" cronjob did not filter out scheduled recordings and added them to the worker queue.
Fix #1190
> Show no scheduled recordings in the videos table

- migrations/051_new_scheme_and_cronjobs.php
- migrations/094_add_acl_cronjob.php
The execution of cronjobs every 120 minutes does not work. This patch changes the period to every 2 hours.
Fix #1238
> Fix periodic execution times of cronjobs

- lib/Models/ScheduleHelper.php
- lib/Models/ScheduledRecordings.php
- lib/Models/VideosUserPerms.php
- lib/Routes/Video/VideoAdd.php
- migrations/102_add_user_to_scheduled_recordings.php
Currently, all dozent get write perms to an uploaded course video or to a scheduled recording. This patch changes this behaviour based on #1216.
close #1216
> Only add owner video perm to uploader or scheduler of the recording

- courseware/vueapp/courseware-plugin-opencast-video.vue
- lib/Models/Videos.php
- lib/RouteMap.php
- lib/Routes/Courseware/CoursewareVideoList.php
- vueapp/components/Videos/VideosTable.vue
- vueapp/store/videos.module.js
Changes:
-  Fix #1225
-  Fix #1219
- Replace some hardcoded course permission checks
- In work place, show only videos with explicit owner perm and no videos from course memberships, close #1219
- Fix incorrect perms in courseware of study groups
- In courseware, show all videos where the user has any explicit permission and all videos from courses with at least instructor perm
> Rework user videos

- lib/Models/ScheduleHelper.php
- lib/Routes/Course/CourseListSchedule.php
- vueapp/components/Courses/CoursesSidebar.vue
- vueapp/components/Schedule/ScheduleList.vue
- vueapp/store/schedule.module.js
Change:
- Show bulk action "Live-Aufzeichnungen planen" only if some of the resources in the listed schedule dates allow live stream.
- Show target playlist selector action if the above condition is met.
Close #1160
> Show livestream bulk action only if schedule dates support livestream

- vueapp/components/Courses/CoursesSidebar.vue
The wordings of selecting the target playlists for recordings and livestreams in "Aufzeichnungen planen" is unclear. This changes should clarify the actions.
> Improve wording for target playlists

- vueapp/components/Playlists/PlaylistsCopyCard.vue
Changes:
- Disable the copy button when playlists are being copied
- Show info notification at the top of the dialog. Apparently, there is no way to scroll to the top of the dialog after pressing the button.
Fix #1244
[Screencast from 2025-02-26 17-08-33.webm](https://github.com/user-attachments/assets/8b6e7d93-fad7-4714-8265-e79cb0c34756)
> Disable copy button during playlist copy process

- lib/Models/Videos.php
If no playlists are migrated to Opencast, the cronjob `opencast_worker` tries to create the playlist in Opencast.
Stack trace:
```
PHP Fatal error: Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /data/studip/os-5.5/public/plugins_packages/elan-ev/OpencastV3/lib/Models/Playlists.php:609
Stack trace:
#0 /data/studip/os-5.5/public/plugins_packages/elan-ev/OpencastV3/lib/Models/Playlists.php(609): array_filter(NULL, Object(Closure))
#1 /data/studip/os-5.5/public/plugins_packages/elan-ev/OpencastV3/lib/Models/Videos.php(1192): Opencast\Models\Playlists->addEntries(Array)
#2 /data/studip/os-5.5/lib/classes/NotificationCenter.class.php(130): Opencast\Models\Videos::addToCoursePlaylist('OpencastCourseS...', Object(stdClass), …
```
> Add missing playlist migration check

- vueapp/components/Videos/VideoRow.vue
Our Opencast system provides no previews on some videos. Therefore, the video title should be clickable on these videos too. The video container is clickable due to https://github.com/elan-ev/studip-opencast-plugin/commit/6505a9956cc78756fdbbf4b2b62051e379a39d36.
> Show clickable video title if no preview is available

- cronjobs/opencast_discover_videos.php
- lib/Models/Videos.php
We don't like the idea of simply deleting videos that are not available in OC from Stud.IP, because problems in the OC search index would trigger this deletion. Instead, these videos will be hidden.
> Hide videos not available in OC but don't delete them from Stud.IP DB

- lib/Models/Helpers.php
This PR fixes #1269,
Due to the issue with database relationship calls not functioning properly in StudIP, I have implemented a simple and direct fix by getting the video owners from **`VideosUserPerms`** based on the **video id**.
> Make sure video owners are notified

- lib/Models/ScheduleHelper.php
It is not necessary to escape the title in the php code as vue automatically escapes html content in templates, see https://vuejs.org/guide/best-practices/security#html-content.
Fix #1322
> Remove html escaping in schedule title

- lib/Models/Videos.php
Replaces the initial 0 duration by the stored video duration in the DB.
Fix #1157
> Show correct video duration

- vueapp/common/upload.service.js
After uploading the video files, a possible error from the oc endpoint `POST ingest/ingest` will be ignored. This PR handles these errors by showing the user an error message instead of a misleading success message.
> Correctly show an error message when uploading a video

- migrations/062_add_config_custom_download.php
This PR fixes #1146.
During the migration we capture the current value of old config and map it into the new config value. Since the old one is boolean we consider only 'never' and 'allow' values for the new one!
> Transfer the value of OPENCAST_ALLOW_MEDIADOWNLOAD config to OPENCAST_MEDIADOWNLOAD

- lib/Models/Videos.php
- lib/RouteMap.php
- lib/Routes/Course/CourseConfig.php
- lib/Routes/Course/CourseSetDefaultVideosVisibility.php
- migrations/109_add_course_config_default_visibility.php
- vueapp/components/Courses/CoursesSidebar.vue
- vueapp/components/Courses/EpisodesDefaultVisibilityDialog.vue
- vueapp/components/Videos/VideoRow.vue
- vueapp/store/opencast.module.js
- vueapp/store/videos.module.js
- vueapp/views/Course.vue
This PR fixes #1316.
- A new course config `OPENCAST_COURSE_DEFAULT_EPISODES_VISIBILITY` via migration no. 109!
- A new **sidebar action** has been added to open a dialog that allows course administrators to configure the **default visibility of episodes** for the course.
- This setting applies only to episodes that currently have their visibility set to **"default"**.
The visibility (for students in a course) can be set to:
- Follow the global setting (`OPENCAST_HIDE_EPISODES`)
- Always be **visible** by default
- Always be **hidden** by default
This change improves flexibility by allowing **per-course control** over the default visibility behavior of episodes, overriding the global default if needed.
> Course Default Visibility feature

- lib/Models/PlaylistSeminars.php
- vueapp/components/Courses/CoursesSidebar.vue
- vueapp/components/Videos/VideosTable.vue
- vueapp/store/playlists.module.js
The issue #1336 is caused by https://gitlab.studip.de/studip/studip/-/issues/5382. This patch casts the values of `allow_download` and `is_default` to boolean values to prevent the javascript condition evaluation of `"0"` as a `true` value, see https://developer.mozilla.org/en-US/docs/Glossary/Truthy.
Fix #1336
> Fix allow media download action

- assets/css/opencast.scss
- lib/Routes/Config/SimpleConfigList.php
- vueapp/components/Videos/Actions/VideoAccess.vue
- vueapp/components/Videos/Actions/VideoEmbeddingCode.vue
- vueapp/components/Videos/VideoRow.vue
- vueapp/components/Videos/VideosTable.vue
Displays a dialog containing an iframe embedding code for external websites. This code is only visible when the video is accessible worldwide.
The oc admin interface offers a size selection. As I do not know whether this function is required, this feature doesn't include such a selection.
Screenshots:
Close #1112
> Video embedding code

- migrations/110_fix_orphaned_previews.php
This PR fixes #1319,
It considts of 2 parts, first the fix for migration 107, in which the problem was that the update only happened when the new preview has a value, which ends up with not updating those previews that have no search/player. The second part, is a fix via a new migration step, by which it reads the previews again and try to locate the orphaned previews with json decoded string and then update them either with null or an URL value.
> Refactor migration logic for preview URLs and add fix for orphaned previews

- vueapp/common/upload.service.js
This patch always shows an error message to users if the upload fails and logs the error into the browser console.
> Show and log video upload errors

- lib/Routes/Opencast/UserRoles.php
These changes only assign individual video ID roles to a user if the user has no permission for these videos via a course role. This should solve problems in Opencast due to many user roles.
Related #1339
> Reduce user roles by using course roles

- lib/Models/Videos.php
Users have no permissions on videos added from the work place. This patch fixes this problem by fetching the episode from opencast if the `$episode` parameter is null.
> Handle null episode in check event acl

- cronjobs/opencast_discover_videos.php
This PR fixes #1271,
It includes a mechanism that checks the integrity of the event before any operation by checking properties against a local array which can be adjusted later on!
> Make sure event has required properties before any operation when discovering events

- lib/Helpers/PlaylistMigration.php
This PR fixes #1255, which enhances playlist migration by enforcing foreign key constraints and make sure the non-nullable columns changes are correctly applied!
PS: the testing environement was a bit confusing for me to make sure that it is working properly, so please test this through!
> Fix playlist sync db issue

- cronjobs/opencast_clear_recycle_bin.php
- cronjobs/opencast_discover_videos.php
- cronjobs/opencast_refresh_scheduling.php
- cronjobs/opencast_sync_acls.php
- cronjobs/opencast_sync_playlists.php
- lib/Helpers/CronjobUtils/OpencastConnectionCheckerTrait.php
- lib/Models/REST/Config.php
- lib/Models/Videos.php
- lib/Providers/OpencastConstants.php
- migrations/112_add_config_option_toggle_unavailable_videos.php
This PR fixes #1374,
Main changes in this PR are:
- Introducing cronjob utils namespace which has a trait for oc conecttion
- A new method: `OCConfig::checkOpencastAPIConnectivity`
- All cronjobs now have a connection checker before processing.
- Video is marked unavailable when they are no longer found in OC.
**NOTE:** It would be very helpful to test all cronjobs and verify that everything works as expected!
> Mark videos unavailable in discovery instead of removing + Opencast API connectivity check in cronjobs

- cronjobs/opencast_sync_acls.php
This PR fixes #1397,
it skips the missing video record during ACL sync worker to ensure seamless processing.
enhance info/loggin of the cronjob.
> Enhance ACL synchronization info and handle missing video records

- lib/Models/Playlists.php
- lib/Routes/Playlist/PlaylistAddVideos.php
- lib/Routes/Playlist/PlaylistRemoveVideos.php
This PR fixes #1384,
Trying to correct the event ACL update when adding or removing video to a playlist which also contains the coresponsing course's ACL.
> Event ACL update correct in playlist section

- cronjobs/opencast_refresh_scheduling.php
- lib/Models/ScheduleHelper.php
- lib/Models/ScheduledRecordings.php
- lib/Routes/Config/ConfigUpdate.php
- vueapp/components/Config/AdminConfigs.vue
- vueapp/components/Config/SchedulingEditModal.vue
- vueapp/components/Config/SchedulingOptions.vue
- vueapp/store/config.module.js
This PR fixes #1300,
Enhance Opencast scheduling functionality with improved event validation and modal management for editing
- Added checks to ensure events exist before every deletion or updating scheduled event in opencast to avoid search index conflicts.
- Introduced a new SchedulingEditModal for editing resources with confirmation prompts.
- Updated SchedulingOptions to handle unsaved changes and resource editing.
- Enhanced state management in Vuex for scheduling-related modals and unsaved changes.
> Rework scheduling mechanism
